const {chromium}=require('playwright'),{spawn,execFileSync}=require('node:child_process'),{build}=require('esbuild'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'verification'),BASE='http://127.0.0.1:4196/semantic-cosmos/',parameters={k_roots:4,tau_in:.72,tau_cross:.72,knn:4,max_wormholes:2,min_cluster_size:2,max_worm_length:.65,relevance_floor:.45,density:.8};
const dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),stats=xs=>{const a=xs.slice().sort((x,y)=>x-y);return {min:a[0],median:a[Math.floor(a.length/2)],max:a.at(-1),mean:a.reduce((s,x)=>s+x,0)/a.length};};
function measurement(data,graph){const pair=[];for(let i=0;i<data.vectors.length;i++)for(let j=i+1;j<data.vectors.length;j++)pair.push(dot(data.vectors[i],data.vectors[j]));const text=graph.nodes.filter(n=>n.kind==='text');return {embedding:data.embedding,pairCosine:stats(pair),norm:stats(data.vectors.map(v=>Math.hypot(...v))),nodes:graph.nodes.length,roots:graph.roots.map(id=>graph.nodes.find(n=>n.id===id).members.length),radius:stats(text.map(n=>Math.hypot(...n.pos))),axes:[0,1,2].map(a=>stats(text.map(n=>n.pos[a])))};}
const instrument=String.raw`let __gpuSubmissions=0;if(globalThis.GPUQueue){const submit=GPUQueue.prototype.submit;GPUQueue.prototype.submit=function(commands){__gpuSubmissions+=commands.length;return submit.call(this,commands);};}const __send=self.postMessage.bind(self);self.postMessage=function(message,...args){if(message.type==='result')message.data.embedding.gpuCommandSubmissions=__gpuSubmissions;return __send(message,...args);};`;
(async()=>{fs.mkdirSync(OUT,{recursive:true});let browser,server,current='initializing',report={status:'RUNNING',baselineCommit:'3fe71bd',synthetic:false,checks:[]};const deadline=setTimeout(()=>{console.error('Backend regression watchdog 240 seconds; last step: '+current);browser?.close().catch(()=>{});server?.kill();process.exit(1)},240000);try{
 server=spawn(process.execPath,['scripts/serve.mjs'],{cwd:ROOT,env:{...process.env,PORT:'4196',COSMOS_BASEPATH:'/semantic-cosmos/'},windowsHide:true,stdio:['ignore','pipe','pipe']});await new Promise((r,j)=>{server.stdout.once('data',r);server.once('error',j);server.stderr.once('data',b=>j(Error(b.toString())))});
 browser=await chromium.launch({headless:process.env.COSMOS_GPU_HEADLESS==='1',executablePath:process.env.COSMOS_CHROMIUM});report.browser=await browser.version();const sys=await(await browser.newBrowserCDPSession()).send('SystemInfo.getInfo');report.gpuDevices=sys.gpu.devices;report.webgpuStatus=sys.gpu.featureStatus.webgpu;
 const raw=JSON.parse(fs.readFileSync(path.join(ROOT,'public/data/news-halfyear-vectors.json'),'utf8')),normalized={records:raw.records,themes:raw.themes,sourceMeta:raw.sourceMeta,warnings:raw.warnings||[]};report.records=normalized.records.length;
 const oldSource=execFileSync('git',['-c','safe.directory='+ROOT.replaceAll('\\','/'),'show','3fe71bd:src/inference.worker.js'],{cwd:ROOT,encoding:'utf8'}),oldBundle=(await build({stdin:{contents:oldSource,resolveDir:path.join(ROOT,'src'),loader:'js'},bundle:true,format:'esm',platform:'browser',target:'es2022',minify:true,write:false})).outputFiles[0].text;
 const actual={};for(const phase of ['before','after']){current=phase+' initialize';console.log('START '+current);const context=await browser.newContext({viewport:{width:1600,height:1000},serviceWorkers:'block'});await context.route('**/assets/inference.worker.js',route=>route.fulfill({body:instrument+(phase==='before'?oldBundle:fs.readFileSync(path.join(ROOT,'dist/assets/inference.worker.js'),'utf8')),contentType:'text/javascript'}));if(phase==='before')await context.route('**/vendor/*',route=>route.fulfill({path:path.join(ROOT,'node_modules/@huggingface/transformers/dist',new URL(route.request().url()).pathname.split('/').at(-1))}));
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(BASE);await page.waitForFunction(()=>window.cosmosDebug?.graph);
 const adapter=await page.evaluate(async()=>{const a=await navigator.gpu?.requestAdapter({powerPreference:'high-performance',forceFallbackAdapter:false});if(!a)return null;const i=a.info;return {vendor:i.vendor,architecture:i.architecture,isFallbackAdapter:i.isFallbackAdapter,features:[...a.features]}});assert.ok(adapter&&!adapter.isFallbackAdapter,'Requires a real WebGPU hardware adapter');report.adapter=adapter;actual[phase]={};report[phase]={};
 if(phase==='after')await page.evaluate(async n=>{const db=await new Promise((r,j)=>{const q=indexedDB.open('semantic-cosmos-v2',1);q.onupgradeneeded=()=>{q.result.createObjectStore('snapshots');q.result.createObjectStore('checkpoints')};q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});for(const device of ['wasm','webgpu']){const input=n.records[0].title+'。'+n.records[0].text,identity=JSON.stringify({model:'Xenova/bge-small-zh-v1.5',revision:'75c43b069aac4d136ba6bc1122f995fedcfd2781',device,pooling:'cls',dtype:'q8',maxTokens:512,text:input}),hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(identity)),key='row:'+Array.from(new Uint8Array(hash),x=>x.toString(16).padStart(2,'0')).join('');await new Promise((r,j)=>{const t=db.transaction('checkpoints','readwrite');t.objectStore('checkpoints').put({row:[1,...Array(511).fill(0)]},key);t.oncomplete=r;t.onerror=()=>j(t.error)});}db.close()},normalized);
 for(const device of ['wasm','webgpu']){current=phase+' '+device+' inference';console.log('START '+current);const data=await page.evaluate(async({n,device})=>await Promise.race([cosmosDebug.embedRecords(n,device),new Promise((_,j)=>setTimeout(()=>j(Error('Backend inference deadline 90 seconds: '+device)),90000))]),{n:normalized,device});assert.equal(data.records.length,73);assert.ok(data.vectors.every(v=>v.length===512&&v.every(Number.isFinite)));if(device==='webgpu')assert.ok(data.embedding.gpuCommandSubmissions>0,'Actual WebGPU queue submissions required');else assert.equal(data.embedding.gpuCommandSubmissions,0);
 current=phase+' '+device+' layout';const graph=await page.evaluate(async({d,p})=>await cosmosDebug.computeGraph(d,p),{d:data,p:parameters});assert.ok(graph.nodes.every(n=>n.pos.every(Number.isFinite)));actual[phase][device]={data,graph};report[phase][device]=measurement(data,graph);
 if(phase==='after'){assert.equal(data.embedding.runtime,'onnxruntime-web/1.30.0');assert.equal(data.embedding.batchSize,1);assert.equal(data.embedding.computedRows,data.embedding.uniqueInputs,'Obsolete row cache must not be reused');}
 await page.locator('#importBtn').click();await page.locator('#jsonPaste').fill(JSON.stringify(graph));await page.locator('#doImport').click();await page.waitForFunction(()=>document.getElementById('importModal').hidden);await page.locator('#modelDevice').selectOption(device);assert.ok((await page.locator('#sourceBadge').innerText()).includes(device==='webgpu'?'WebGPU':'WASM / CPU'));if(device==='webgpu')assert.equal((await page.locator('#workspaceStatus').innerText()).includes('旧 WebGPU'),phase==='before');await page.locator('#depth').fill('8');await page.locator('#resetView').click();await page.evaluate(()=>Object.assign(cosmosDebug.camera,{yaw:-.38,pitch:.24,zoom:1.2,focus:[0,0,0]}));await page.locator('#zoomIn').click();await page.locator('#rotate').uncheck();await page.waitForTimeout(100);const camera=await page.evaluate(()=>cosmosDebug.camera);report[phase][device].camera=camera;await page.screenshot({path:path.join(OUT,'gpu-'+phase+'-'+device+'-73.png')});
 console.log('MEASURE '+JSON.stringify({phase,device,cosine:report[phase][device].pairCosine,radius:report[phase][device].radius,submissions:data.embedding.gpuCommandSubmissions,ms:data.embedding.durationMs}));
 }
 const a=actual[phase].wasm.data,b=actual[phase].webgpu.data;report[phase].alignedCosine=stats(a.vectors.map((v,i)=>dot(v,b.vectors[i])));assert.deepEqual(report[phase].wasm.camera,report[phase].webgpu.camera);if(phase==='after'){
 const delta=[];for(let i=0;i<73;i++)for(let j=i+1;j<73;j++)delta.push(Math.abs(dot(a.vectors[i],a.vectors[j])-dot(b.vectors[i],b.vectors[j])));report.after.pairCosineDifference=stats(delta);assert.ok(report.after.alignedCosine.min>.99);assert.ok(report.after.alignedCosine.median>.998);assert.ok(report.after.pairCosineDifference.mean<.005);assert.ok(report.after.pairCosineDifference.max<.03);const radiusRatio=report.after.webgpu.radius.median/report.after.wasm.radius.median;assert.ok(radiusRatio>.9&&radiusRatio<1.1,'Same scale without WebGPU contraction');report.checks.push('73 real records: aligned vectors, pairwise cosine, finite coordinates and same camera/scale; hardware GPU queue submissions');
 for(const device of ['wasm','webgpu']){current='warm cache '+device;const warm=await page.evaluate(async({n,device})=>await cosmosDebug.embedRecords(n,device),{n:normalized,device});assert.equal(warm.embedding.computedRows,0);assert.deepEqual(warm.vectors,actual.after[device].data.vectors);report.after[device].warmMs=warm.embedding.durationMs;}
 const append=await page.evaluate(async n=>await cosmosDebug.embedRecords({...n,records:[...n.records,{id:'backend-synthetic-cache-check',title:'合成缓存检查',text:'此条为合成测试数据，不是真实新闻。'},{...n.records[0],id:'duplicate-backend-cache-check'}]},'webgpu'),normalized);assert.equal(append.embedding.computedRows,1);assert.deepEqual(append.vectors.slice(0,73),b.vectors);assert.deepEqual(append.vectors.at(-1),b.vectors[0]);report.checks.push('old runtime row cache invalidated; warm caches exact; appended and duplicate input preserves previous vectors');
 await page.locator('#vendorFilter').selectOption('Anthropic');await page.locator('#search').fill('tokenizer');await page.locator('#tree button').filter({hasText:'Opus 4.7'}).first().click();await page.waitForFunction(()=>cosmosDebug.graph.map.get(cosmosDebug.selected)?.kind==='text');await page.locator('#focusBtn').click();await page.evaluate(async()=>{await cosmosDebug.view.enter(cosmosDebug.view.nodeFor(cosmosDebug.selected),false);});await page.locator('#detailTitle').scrollIntoViewIfNeeded();await page.waitForTimeout(100);assert.ok(await page.evaluate(()=>cosmosDebug.projected.some(p=>p.n.kind==='satellite')));await page.screenshot({path:path.join(OUT,'gpu-fixed-event-satellites.png')});await page.locator('#detailTitle').evaluate(e=>e.scrollIntoView({block:'start'}));await page.screenshot({path:path.join(OUT,'gpu-fixed-evidence-detail.png'),clip:{x:1309,y:88,width:291,height:912}});report.checks.push('fixed real GPU graph: vendor search navigation, source satellite, dates/evidence/limitations/detail');
 }assert.deepEqual(errors,[]);await context.close();}
 report.status='PASS';console.log(JSON.stringify({status:report.status,records:report.records,checks:report.checks,beforeAligned:report.before.alignedCosine,afterAligned:report.after.alignedCosine,pairDifference:report.after.pairCosineDifference,adapter:report.adapter},null,2));
 }catch(e){report.status='FAIL';report.failedStep=current;report.error=e.stack;throw e;}finally{clearTimeout(deadline);fs.writeFileSync(path.join(OUT,'gpu-backend-results.json'),JSON.stringify(report,null,2));await browser?.close();server?.kill();}})().catch(e=>{console.error(e);process.exitCode=1});
