import nodeTest from 'node:test';
const test=(name,fn)=>nodeTest(name,{timeout:10000},()=>{console.log('START '+name);return fn();});
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {constructHierarchy,visibleFrontier,LEAF_CAPACITY} from '../src/hierarchy.js';
import {normalizeTexts,validateVectors,DEFAULT_PARAMETERS} from '../src/adapters.js';
import {synthetic} from '../scripts/benchmark.mjs';
import {openCatalog} from '../src/catalog.js';
const source=JSON.parse(fs.readFileSync('public/data/news-halfyear.json')),vectors=JSON.parse(fs.readFileSync('public/data/news-halfyear-vectors.json'));
function graph(n){const g=constructHierarchy(synthetic(n),DEFAULT_PARAMETERS);g.map=new Map(g.nodes.map(n=>[n.id,n]));return g;}
test('73 records retain every original record and align with embedding IDs',()=>{const old=JSON.parse(fs.readFileSync('public/data/news-source.json'));assert.equal(source.items.length,73);assert.equal(source.meta.item_count,73);assert.deepEqual(source.items.map(x=>x.id),vectors.records.map(x=>x.id));for(const r of old.items)assert.deepEqual(source.items.find(x=>x.id===r.id).legacy_record,r);assert.equal(validateVectors(vectors.records,vectors.vectors),512);});
test('evidence has precise URLs, explicit uncertainty, deduplicated event keys',()=>{const keys=new Set();for(const r of source.items){assert.ok(!keys.has(r.event_key));keys.add(r.event_key);assert.ok(['官方确认','独立测试','用户报告','未证实观点'].includes(r.evidence_category));assert.ok(Object.hasOwn(r,'published_date'));assert.ok(r.limitations);assert.ok(r.sources.length);for(const s of r.sources){assert.ok(/^https?:\/\//.test(s.url));assert.ok(s.evidence_category);}}assert.equal(source.items.find(r=>r.id==='2026-07-meta-test-misconfiguration').event_date,'2026-07');assert.equal(source.items.filter(r=>!r.legacy_record&&!r.event_date).length,5);});
test('normalization preserves evidence and rejects empty, repeated ID, zero and huge vectors',()=>{const x=normalizeTexts(source);assert.deepEqual(x.records[0].sources,source.items[0].sources);assert.equal(x.records[0].limitations,source.items[0].limitations);assert.throws(()=>normalizeTexts({texts:[]}),/1–20000/);assert.throws(()=>normalizeTexts({texts:[{id:'x',text:'中文'},{id:'x',text:'重复'}]}),/重复/);assert.throws(()=>validateVectors([{id:'x'}],[[0,0]]),/无效/);assert.throws(()=>validateVectors(Array(20000),[Array(4096)]),/行数/);});
test('10k synthetic hierarchy preserves documents, caps local work and never allocates a global pair matrix',()=>{const g=graph(10000),h=g.metadata.hierarchy;assert.equal(g.nodes.filter(n=>n.kind==='text').length,10000);assert.ok(g.nodes.filter(n=>n.kind==='leaf').every(n=>n.members.length<=LEAF_CAPACITY));assert.ok(h.maxLocalPairs<=496);assert.equal(h.globalPairMatrix,false);assert.ok(h.comparisons<10000*100);for(const n of g.nodes){assert.ok(n.pos.every(Number.isFinite));assert.ok(n.children.length<=8||n.kind==='leaf');if(n.parent)assert.ok(g.map.get(n.parent).children.includes(n.id));}});
test('semantic paths stable under record reorder and append at top level',()=>{const d=synthetic(600),a=constructHierarchy(d,DEFAULT_PARAMETERS),reverse={...d,records:d.records.slice().reverse(),vectors:d.vectors.slice().reverse()},b=constructHierarchy(reverse,DEFAULT_PARAMETERS),c=constructHierarchy({...d,records:d.records.concat(synthetic(1).records.map(r=>({...r,id:'new'}))),vectors:d.vectors.concat(synthetic(1).vectors)},DEFAULT_PARAMETERS);const roots=g=>new Map(g.nodes.filter(n=>n.kind==='text').map(n=>[n.documentId,n.root]));assert.deepEqual(roots(a),roots(b));for(const [id,root] of roots(a))assert.equal(roots(c).get(id),root);});
test('identical and cancelling vectors terminate with bounded shards and useful individual positions',()=>{for(const n of [1,1000]){const d=synthetic(n,4);d.vectors=d.vectors.map(()=>[1,0,0,0]);const g=constructHierarchy(d,DEFAULT_PARAMETERS);assert.equal(g.nodes.filter(n=>n.kind==='text').length,n);assert.ok(g.nodes.every(n=>n.depth<25));assert.ok(g.nodes.filter(n=>n.kind==='leaf').every(n=>n.members.length<=32));assert.equal(new Set(g.nodes.filter(n=>n.kind==='text').map(n=>n.pos.join(','))).size,n);}const d=synthetic(64,2);d.vectors=d.vectors.map((_,i)=>i%2?[1,0]:[-1,0]);assert.doesNotThrow(()=>constructHierarchy(d,DEFAULT_PARAMETERS));});
test('frontier respects budgets, zoom, filters and prioritizes any searched document',()=>{const g=graph(1000),id=g.nodes.filter(n=>n.kind==='text').at(-1).id;const low=visibleFrontier(g,{depth:1,zoom:.3}),high=visibleFrontier(g,{depth:10,zoom:2,budget:100});assert.ok(![...low].some(id=>g.map.get(id).kind==='text'));assert.ok(high.size<=100);assert.ok(g.roots.every(id=>high.has(id)));assert.ok(visibleFrontier(g,{depth:0,zoom:.3,focus:id,budget:30}).has(id));assert.equal(visibleFrontier(g,{matches:()=>false}).size,0);});
test('catalog fetches just one shard, coalesces requests and hydrates portable records with aligned vectors',async()=>{const fetchBefore=globalThis.fetch,seen=[],n={id:'doc:a',kind:'text',members:['a'],children:[],documentId:'a',root:'r',parent:'r',depth:1,label:'中文',pos:[1,2,3]},record={id:'a',title:'中文',text:'证据',sources:[{url:'https://example.org/source'}]},manifest={graph:{roots:['r'],nodes:[{id:'r',kind:'root',parent:null,root:'r',depth:0,label:'根',pos:[0,0,0],members:['a'],children:['doc:a']}],edges:[],metadata:{}},index:[{record:{id:'a',title:'中文',text:'证据'},nodeId:'doc:a',parent:'r',chunk:'one'}],vectors:'data/vectors.json'};globalThis.fetch=async url=>{seen.push(String(url));return {ok:true,json:async()=>String(url).includes('chunks')?{nodes:[n],texts:[record],edges:[{source:'r',target:'doc:a',type:'tree'}]}:{records:[record],vectors:[[1,0]],themeVectors:[],embedding:{}}};};try{const c=openCatalog(manifest);c.graph.map=new Map(c.graph.nodes.map(n=>[n.id,n]));c.graph.docs=new Map(c.graph.texts.map(t=>[t.id,t]));assert.equal(seen.length,0);await Promise.all([c.ensure('doc:a'),c.ensure('doc:a')]);assert.equal(seen.length,1);assert.deepEqual(c.graph.docs.get('a').sources,record.sources);await c.hydrate();await c.hydrate();assert.equal(seen.length,2);assert.deepEqual(c.graph.vectors,[[1,0]]);}finally{globalThis.fetch=fetchBefore;}});
