import test from 'node:test';
import assert from 'node:assert/strict';
import {frame,ellipse,at,path,OrbitClock,OrbitalDisplay} from '../src/orbits.js';
const distance=(a,b)=>Math.hypot(...a.map((x,i)=>x-b[i]));
const graph=()=>({map:new Map([['star',{id:'star',kind:'leaf',pos:[10,20,30]}],['planet',{id:'planet',parent:'star',kind:'text',pos:[18,23,29]}]])});
test('seeded 3D planes vary between systems and elliptical periods close',()=>{const a=frame('a'),b=frame('b');assert.deepEqual(a,frame('a'));assert.ok(distance(a.v,b.v)>.1);const orbit={...a,a:10,e:.2,center:[1,2,3],phase:0,period:30};assert.ok(distance(at(orbit,0),at(orbit,30))<1e-10);assert.ok(Math.abs(Math.hypot(...ellipse(orbit,0))-8)<1e-10);assert.ok(Math.abs(Math.hypot(...ellipse(orbit,Math.PI))-12)<1e-10);assert.ok(distance(path(orbit)[0],path(orbit).at(-1))<1e-10);});
test('clock is frame independent, pause/resume/speed and background are continuous',()=>{const make=fps=>{const c=new OrbitClock();c.tick(0);for(let i=1;i<=fps*8;i++)c.tick(i*1000/fps);return c;};assert.ok(Math.abs(make(30).time-make(144).time)<1e-10);const c=make(60);c.freeze('s');const old=c.seconds('s');c.tick(9000);assert.equal(c.seconds('s'),old);c.resume('s');assert.equal(c.seconds('s'),old);c.tick(10000);assert.equal(c.seconds('s'),old+1);c.hidden=true;c.sync();c.tick(1000000);c.hidden=false;c.sync();c.tick(1000100);assert.ok(Math.abs(c.time-10)<1e-10);c.speed=2;c.tick(1000600);assert.ok(Math.abs(c.time-11)<1e-10);c.paused=true;c.tick(1001600);assert.ok(Math.abs(c.time-11)<1e-10);c.reset();assert.equal(c.time,0);});
test('initial display equals semantic position, satellites compose parent motion, no graph mutation',()=>{const g=graph(),before=JSON.stringify([...g.map.values()]),d=new OrbitalDisplay(g),n=g.map.get('planet');assert.ok(distance(d.position(n),n.pos)<1e-10);d.clock.tick(0);d.clock.tick(2500);assert.ok(distance(d.position(n),n.pos)>.1);const satellite=d.satellitePosition(n,0),offset=at(d.satellite(n,0),2.5);assert.ok(distance(satellite,d.position(n).map((x,i)=>x+offset[i]))<1e-10);d.reading(n);const frozen=d.position(n);d.clock.tick(15000);assert.deepEqual(d.position(n),frozen);d.reading(null);assert.deepEqual(d.position(n),frozen);d.clock.tick(16000);assert.ok(distance(d.position(n),frozen)>.1);assert.equal(JSON.stringify([...g.map.values()]),before);assert.deepEqual(d.position(n,false),n.pos);});
test('definitions are lazy, bounded and consistent across graph backend metadata',()=>{const g=graph(),a=new OrbitalDisplay(g),b=new OrbitalDisplay({...g,metadata:{embedding:{backend:'webgpu'}}});assert.equal(a.cache.size,0);assert.deepEqual(a.position(g.map.get('planet')),b.position(g.map.get('planet')));assert.equal(a.cache.size,1);const o=a.orbit(g.map.get('planet'));assert.ok(o.a<=24&&o.e<.3);assert.ok(o.v[1]!==0);});
