const {chromium}=require('playwright'),{spawn,execFileSync}=require('node:child_process'),{build}=require('esbuild'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'verification'),BASE='http://127.0.0.1:4197/';
const percentile=(a,p)=>a.slice().sort((x,y)=>x-y)[Math.floor((a.length-1)*p)],distance=(a,b)=>Math.hypot(...a.map((x,i)=>x-b[i]));
async function sample(page,ms=1800){return page.evaluate(ms=>new Promise(resolve=>{const start=performance.now(),draws=[],intervals=[];let previous=-1,lastDraw=-1;function f(t){const c=cosmosDebug.counters;if(c.drawCount===undefined||c.drawCount!==lastDraw){if(previous>=0)intervals.push(t-previous);previous=t;lastDraw=c.drawCount;draws.push(c.drawDurationMs);}if(t-start<ms)requestAnimationFrame(f);else resolve({draws,intervals,visible:c.visible,definitions:c.orbitDefinitions||0});}requestAnimationFrame(f)}),ms);}
async function importGraph(page,g){const fixture=path.join(OUT,'orbit-fixture.json');fs.writeFileSync(fixture,JSON.stringify(g));await page.locator('#importBtn').click();await page.locator('#jsonPaste').fill('');await page.locator('#jsonFile').setInputFiles(fixture);await page.locator('#doImport').click();await page.waitForFunction(()=>document.getElementById('importModal').hidden,{},{timeout:20000});}
(async()=>{let server,browser,current='initialization';const report={status:'RUNNING',baseline:'f2ee556',checks:[],performance:[]},errors=[];fs.mkdirSync(OUT,{recursive:true});const deadline=setTimeout(()=>{console.error('Orbit QA watchdog 180s at '+current);browser?.close().catch(()=>{});server?.kill();process.exit(1)},180000);try{
 server=spawn(process.execPath,['scripts/serve.mjs'],{cwd:ROOT,env:{...process.env,PORT:'4197'},windowsHide:true,stdio:['ignore','pipe','pipe']});await new Promise((r,j)=>{server.stdout.once('data',r);server.once('error',j);server.stderr.once('data',b=>j(Error(b.toString())))});
 browser=await chromium.launch({headless:false,executablePath:process.env.COSMOS_CHROMIUM});report.browser=await browser.version();
 const {synthetic}=await import('../scripts/benchmark.mjs'),{constructHierarchy}=await import('../src/hierarchy.js'),{DEFAULT_PARAMETERS}=await import('../src/adapters.js');const fixtures=new Map([1000,10000].map(n=>[n,constructHierarchy(synthetic(n),DEFAULT_PARAMETERS)]));
 const oldSource=execFileSync('git',['show','f2ee556:src/app.js'],{cwd:ROOT,encoding:'utf8'}),oldBundle=(await build({stdin:{contents:oldSource,resolveDir:path.join(ROOT,'src'),loader:'js'},bundle:true,format:'esm',platform:'browser',minify:true,write:false})).outputFiles[0].text;
 for(const phase of ['before','after']){current=phase+' performance';console.log('START '+current);const context=await browser.newContext({viewport:{width:1500,height:1000},serviceWorkers:'block'});if(phase==='before')await context.route('**/assets/app.js',r=>r.fulfill({body:oldBundle,contentType:'text/javascript'}));const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(BASE);await page.waitForFunction(()=>window.cosmosDebug?.graph);await page.evaluate(()=>cosmosDebug.hydrate());
  for(const n of [73,1000,10000]){if(n!==73)await importGraph(page,fixtures.get(n));await page.locator('#depth').fill('8');await page.evaluate(()=>{cosmosDebug.camera.zoom=2;document.getElementById('rotate').checked=true;document.getElementById('rotate').dispatchEvent(new Event('change'));});await page.waitForTimeout(100);const s=await sample(page);assert.ok(s.visible<=600);report.performance.push({phase,n,synthetic:n!==73,mode:phase==='before'?'f2ee556 static positions + camera rotation':'3D orbits + camera rotation',visible:s.visible,drawMedianMs:percentile(s.draws,.5),drawP95Ms:percentile(s.draws,.95),renderIntervalMedianMs:percentile(s.intervals,.5),definitions:s.definitions});}
  await context.close();
 }
 current='orbital interaction';console.log('START '+current);const context=await browser.newContext({viewport:{width:1600,height:1000},serviceWorkers:'block'});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(BASE);await page.waitForFunction(()=>window.cosmosDebug?.graph);await page.evaluate(()=>cosmosDebug.hydrate());await page.locator('#depth').fill('8');await page.locator('#orbitReading').uncheck();await page.evaluate(()=>{cosmosDebug.camera.zoom=2;});await page.locator('#orbitSpeed').fill('2');
 await page.evaluate(()=>{const stream=document.getElementById('cosmos').captureStream(20),mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm;codecs=vp8';window.__orbitChunks=[];window.__orbitRecorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:1400000});__orbitRecorder.ondataavailable=e=>{if(e.data.size)__orbitChunks.push(e.data)};__orbitRecorder.start(500);});
 const before=await page.evaluate(()=>JSON.stringify(cosmosDebug.exportableUniverse().nodes));await page.waitForTimeout(1100);const first=await page.evaluate(()=>cosmosDebug.projected.filter(p=>p.n.kind==='text').map(p=>({id:p.n.id,world:p.world})));await page.waitForTimeout(700);const second=await page.evaluate(()=>cosmosDebug.projected.filter(p=>p.n.kind==='text').map(p=>({id:p.n.id,world:p.world})));assert.ok(first.some(p=>distance(p.world,second.find(x=>x.id===p.id).world)>.1));assert.equal(await page.evaluate(()=>JSON.stringify(cosmosDebug.exportableUniverse().nodes)),before);const normals=await page.evaluate(()=>cosmosDebug.drawnOrbits.map(o=>o.normal));assert.ok(normals.some(v=>distance(v,normals[0])>.3));report.checks.push('real 73 planets move on multiple seeded 3D planes; exported semantic nodes unchanged');
 await page.screenshot({path:path.join(OUT,'orbits-multiple-planes.png')});await page.locator('#orbitPause').click();await page.waitForTimeout(60);const frozen=await page.evaluate(()=>cosmosDebug.projected.filter(p=>p.n.kind==='text').map(p=>p.world));await page.waitForTimeout(300);assert.deepEqual(await page.evaluate(()=>cosmosDebug.projected.filter(p=>p.n.kind==='text').map(p=>p.world)),frozen);await page.locator('#orbitPause').click();
 await page.locator('#vendorFilter').selectOption('Anthropic');await page.locator('#search').fill('tokenizer');await page.locator('#tree button[aria-label^="行星"]').filter({hasText:'Opus 4.7'}).first().click();await page.locator('#orbitReading').check();const selected=await page.evaluate(()=>cosmosDebug.selected),position=await page.evaluate(()=>cosmosDebug.orbital.position(cosmosDebug.graph.map.get(cosmosDebug.selected)));await page.waitForTimeout(400);assert.deepEqual(await page.evaluate(()=>cosmosDebug.orbital.position(cosmosDebug.graph.map.get(cosmosDebug.selected))),position);await page.locator('#orbitReading').uncheck();const resumed=await page.evaluate(()=>cosmosDebug.orbital.position(cosmosDebug.graph.map.get(cosmosDebug.selected)));assert.ok(distance(position,resumed)<1,'resume is continuous within elapsed UI frame');await page.waitForTimeout(1000);
 assert.ok(await page.evaluate(()=>cosmosDebug.projected.some(p=>p.n.kind==='satellite')), 'Selected event must expose source satellites');assert.ok(await page.evaluate(()=>cosmosDebug.projected.filter(p=>p.n.kind==='satellite').every(p=>{const q=cosmosDebug.project(p.world);return Math.hypot(q.x-p.x,q.y-p.y)<1e-8;})));await page.screenshot({path:path.join(OUT,'orbits-event-and-satellites.png')});await page.locator('#detailMeta').evaluate(e=>e.scrollIntoView({block:'start'}));await page.screenshot({path:path.join(OUT,'orbits-evidence-detail.png')});report.checks.push('pause/resume, speed, reading freeze, search focus and true 3D source-satellite projection');
 await page.locator('#vendorFilter').selectOption('');await page.locator('#search').fill('');await page.locator('#resetView').click();await page.locator('#orbitReset').click();assert.ok(await page.evaluate(()=>cosmosDebug.orbital.clock.time)<.3);await page.locator('#zoomIn').click();await page.locator('#zoomOut').click();const box=await page.locator('#cosmos').boundingBox();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.6,box.y+box.height*.55,{steps:8});await page.mouse.up();await page.waitForTimeout(700);
 // Actual canvas video, not an image sequence generated from desired behavior.
 await page.locator('#depth').fill('8');await page.evaluate(()=>{cosmosDebug.camera.zoom=2;});await page.locator('#vendorFilter').selectOption('Anthropic');await page.locator('#search').fill('tokenizer');await page.locator('#tree button[aria-label^="行星"]').filter({hasText:'Opus 4.7'}).first().click();await page.locator('#orbitReading').uncheck();await page.waitForTimeout(5000);const video=await page.evaluate(()=>new Promise(resolve=>{__orbitRecorder.onstop=()=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.readAsDataURL(new Blob(__orbitChunks,{type:'video/webm'}));__orbitRecorder.stream.getTracks().forEach(t=>t.stop());};__orbitRecorder.stop();}));fs.writeFileSync(path.join(OUT,'semantic-cosmos-orbits.webm'),Buffer.from(video,'base64'));report.recording={type:'native canvas.captureStream + MediaRecorder',mime:'video/webm',captureFps:20,bytes:Buffer.from(video,'base64').length};await context.close();
 current='mobile, background and reduced motion';console.log('START '+current);const mobile=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block',reducedMotion:'reduce'}),m=await mobile.newPage();m.on('pageerror',e=>errors.push(e.message));await m.goto(BASE);await m.waitForFunction(()=>window.cosmosDebug?.graph);assert.equal(await m.locator('#orbitEnabled').isChecked(),false);await m.locator('#orbitEnabled').check();await importGraph(m,fixtures.get(10000));await m.locator('#depth').fill('8');await m.evaluate(()=>{cosmosDebug.camera.zoom=2;});await m.waitForTimeout(400);assert.ok(await m.evaluate(()=>cosmosDebug.projected.length<=240));assert.ok(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const slow=await mobile.newCDPSession(m);await slow.send('Emulation.setCPUThrottlingRate',{rate:4});const low=await sample(m,1400);report.lowPerformance={n:10000,synthetic:true,viewport:'390x844',cpuThrottle:4,visible:low.visible,drawMedianMs:percentile(low.draws,.5),drawP95Ms:percentile(low.draws,.95),renderIntervalMedianMs:percentile(low.intervals,.5)};await slow.send('Emulation.setCPUThrottlingRate',{rate:1});await m.screenshot({path:path.join(OUT,'orbits-mobile.png'),fullPage:true});report.checks.push('390px mobile 10k synthetic <=240 nodes; reduced-motion defaults to static and permits explicit enable');await mobile.close();
 const bg=await browser.newContext({serviceWorkers:'block'}),p=await bg.newPage();await p.goto(BASE);await p.waitForFunction(()=>window.cosmosDebug?.graph);const t=await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));document.dispatchEvent(new Event('freeze'));return cosmosDebug.orbital.clock.time;});await p.waitForTimeout(700);assert.equal(await p.evaluate(()=>cosmosDebug.orbital.clock.time),t);await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('resume'));document.dispatchEvent(new Event('visibilitychange'));});await p.waitForTimeout(100);const recovery=await p.evaluate(()=>cosmosDebug.orbital.clock.time);assert.ok(recovery-t<.3);report.background={method:'controlled DOM visibility/freeze/resume events',hiddenMs:700,clockAdvanceSeconds:recovery-t,actualDesktopVisibility:'NOT VERIFIED: this Windows Edge environment reports document.hidden=false after owned-window minimization and emits no visibility/freeze events; CDP freeze of visible page does not suspend it'};report.checks.push('controlled background lifecycle excludes hidden elapsed time; native desktop background transition has an explicit environment limitation');await bg.close();
 current='real CPU and hardware WebGPU orbital regression';console.log('START '+current);const gpu=await browser.newContext({viewport:{width:1500,height:1000},serviceWorkers:'block'});await gpu.route('**/assets/inference.worker.js',r=>r.fulfill({body:'let submissions=0;if(globalThis.GPUQueue){const original=GPUQueue.prototype.submit;GPUQueue.prototype.submit=function(commands){submissions+=commands.length;return original.call(this,commands);};}const send=self.postMessage.bind(self);self.postMessage=function(m,...args){if(m.type==="result")m.data.embedding.gpuCommandSubmissions=submissions;return send(m,...args);};'+fs.readFileSync(path.join(ROOT,'dist/assets/inference.worker.js'),'utf8'),contentType:'text/javascript'}));const gpage=await gpu.newPage();gpage.on('pageerror',e=>errors.push(e.message));await gpage.goto(BASE);await gpage.waitForFunction(()=>window.cosmosDebug?.graph);const adapter=await gpage.evaluate(async()=>{const a=await navigator.gpu.requestAdapter({forceFallbackAdapter:false,powerPreference:'high-performance'});return a?{vendor:a.info.vendor,architecture:a.info.architecture,isFallbackAdapter:a.info.isFallbackAdapter}:null;});assert.ok(adapter&&!adapter.isFallbackAdapter,'Actual hardware WebGPU required');report.adapter=adapter;
 const raw=JSON.parse(fs.readFileSync(path.join(ROOT,'public/data/news-halfyear-vectors.json'),'utf8')),input={records:raw.records,themes:raw.themes,sourceMeta:raw.sourceMeta,warnings:raw.warnings||[]},vectors={},backend=[];
 for(const device of ['wasm','webgpu']){console.log('START orbital '+device+' inference');const data=await gpage.evaluate(async({input,device})=>Promise.race([cosmosDebug.embedRecords(input,device),new Promise((_,reject)=>setTimeout(()=>reject(Error('Orbit inference timeout '+device)),60000))]),{input,device});vectors[device]=data.vectors;assert.equal(data.records.length,73);if(device==='webgpu')assert.ok(data.embedding.gpuCommandSubmissions>0);const graph=await gpage.evaluate(async data=>await cosmosDebug.computeGraph(data,cosmosDebug.graph.parameters),data);await importGraph(gpage,graph);await gpage.locator('#orbitReading').uncheck();await gpage.locator('#depth').fill('8');await gpage.evaluate(()=>{cosmosDebug.camera.zoom=2;cosmosDebug.orbital.clock.time=4;cosmosDebug.orbital.clock.paused=true;document.getElementById('showTexts').dispatchEvent(new Event('change'));});await gpage.waitForTimeout(80);assert.ok(await gpage.evaluate(()=>cosmosDebug.projected.filter(p=>p.n.kind==='text').every(p=>{const expected=cosmosDebug.project(cosmosDebug.orbital.position(p.n));return Math.hypot(p.x-expected.x,p.y-expected.y)<1e-7;})));backend.push({device,embedding:data.embedding,nodes:graph.nodes.length});}
 const cosines=vectors.wasm.map((v,i)=>v.reduce((s,x,j)=>s+x*vectors.webgpu[i][j],0));assert.ok(Math.min(...cosines)>.99);report.backends=backend;report.alignedCosine={min:Math.min(...cosines),median:percentile(cosines,.5)};report.checks.push('all 73 real CPU/hardware-WebGPU embeddings aligned; same 3D position projection path and GPU queue submissions verified');await gpu.close();
 assert.deepEqual(errors,[]);report.status='PASS';report.errors=errors;console.log(JSON.stringify(report,null,2));
 }catch(e){report.status='FAIL';report.failedStep=current;report.error=e.stack?.slice(0,5000);throw e;}finally{clearTimeout(deadline);fs.writeFileSync(path.join(OUT,'orbits-browser-results.json'),JSON.stringify(report,null,2));await browser?.close();server?.kill();}})().catch(e=>{console.error(String(e.message).slice(0,800));process.exitCode=1});
