import {dot,unit,clamp,random} from './core.js';
import {SPACE_SCALE,shortWorm} from './space.js';
import {datasetFrom,normalizeTexts,MODEL_ID,DEFAULT_PARAMETERS} from './adapters.js';
import {computeGraph,embedRecords,cancelJobs} from './workers-client.js';
import {saveWorkspace,loadWorkspace,requestPersistence} from './storage.js';

const $=id=>document.getElementById(id);
function parameters(){return {k_roots:+$('kRoots').value,tau_in:+$('tauIn').value,tau_cross:+$('tauCross').value,knn:+$('knn').value,max_wormholes:+$('maxWorm').value,min_cluster_size:+$('minCluster').value,max_worm_length:+$('wormLength').value,relevance_floor:+$('relevanceFloor').value,density:+$('density').value}}
const COLORS=['#9be4ce','#80bde8','#e8bf7a','#b3a6ee','#e89ca5','#9fcea0','#cdbaa5','#90c8d5'];
const KIND={root:'根主题',branch:'中间主题',leaf:'叶主题',text:'文本单元'};
let dataset=null, universe=null, selected=null, hovered=null, projected=[], needsDraw=true, previousFocus=null,drawnWorms=[];
const camera={yaw:-.38,pitch:.18,zoom:1,focus:[0,0,0]};
let W=0,H=0,dpr=1,lastTime=0,pinchLast=0,dragMoved=false;
const canvas=$('cosmos'),ctx=canvas.getContext('2d'),pointers=new Map();
function graphScale(g=universe){return g?.metadata?.space?.scale??g?.metadata?.sphere?.radius??SPACE_SCALE;}
function prepareGraph(g){
 if(!g||!Array.isArray(g.nodes)||!Array.isArray(g.edges)||!Array.isArray(g.roots)||!Array.isArray(g.texts))throw Error('图谱需要 roots、nodes、edges 与 texts 数组');
 if(!g.nodes.length||g.nodes.length>5000||g.edges.length>30000)throw Error('图谱支持 1–5000 节点、最多 30000 条边');
 const ids=new Map();g.nodes.forEach(n=>{if(!n||typeof n.id!=='string'||!n.id||ids.has(n.id))throw Error('图谱节点 ID 缺失或重复');if(!KIND[n.kind]||typeof n.label!=='string')throw Error('节点类型或名称无效');if(!Array.isArray(n.pos)||n.pos.length!==3||n.pos.some(x=>!Number.isFinite(x)||Math.abs(x)>1e7))throw Error('节点坐标无效');if(n.localRadius!==undefined&&(!Number.isFinite(n.localRadius)||n.localRadius<=0||n.localRadius>1e5))throw Error('主题邻域半径无效');if(!Array.isArray(n.children)||!Array.isArray(n.members))throw Error('节点缺少 children 或 members');if(!Number.isInteger(n.depth)||n.depth<0||n.depth>100)throw Error('节点层级无效');ids.set(n.id,n)});
 const rootSet=new Set(g.roots);if(rootSet.size!==g.roots.length||!rootSet.size)throw Error('根主题为空或重复');g.roots.forEach(id=>{const n=ids.get(id);if(!n||n.kind!=='root'||n.parent!==null||n.root!==id||n.depth!==0)throw Error('根主题引用无效')});
 g.nodes.forEach(n=>{if(!rootSet.has(n.root))throw Error('节点根主题不存在');if(n.kind==='root'&&!rootSet.has(n.id))throw Error('根节点未在 roots 中声明');if(n.kind!=='root'){const parent=ids.get(n.parent);if(!parent||parent.root!==n.root||parent.depth+1!==n.depth||!parent.children.includes(n.id))throw Error('父子层级或根归属不一致')}if(new Set(n.children).size!==n.children.length)throw Error('重复子节点');n.children.forEach(id=>{if(!ids.has(id)||ids.get(id).parent!==n.id)throw Error('子节点引用不一致')});if(n.kind==='text'&&n.children.length)throw Error('文本节点不能有子节点')});
 const visited=new Set();function visit(id){if(visited.has(id))throw Error('图谱包含循环或多重父节点');visited.add(id);ids.get(id).children.forEach(visit)}g.roots.forEach(visit);if(visited.size!==ids.size)throw Error('图谱存在未连接节点');
 const docs=new Map();g.texts.forEach(t=>{if(!t||typeof t.id!=='string'||docs.has(t.id)||typeof t.text!=='string'||typeof t.title!=='string')throw Error('图谱文本格式错误或 ID 重复');docs.set(t.id,t)});g.nodes.forEach(n=>{if(n.members.some(id=>!docs.has(id))||new Set(n.members).size!==n.members.length)throw Error('节点成员文本不存在或重复');if(n.kind==='text'&&(!docs.has(n.documentId)||n.members.length!==1||n.members[0]!==n.documentId))throw Error('文本节点缺少有效 documentId')});
 g.parameters={...DEFAULT_PARAMETERS,...g.parameters};
 if(!Number.isFinite(g.parameters.max_worm_length)||g.parameters.max_worm_length<.1||g.parameters.max_worm_length>1.5||!Number.isFinite(g.parameters.relevance_floor)||g.parameters.relevance_floor<0||g.parameters.relevance_floor>.95)throw Error('导入的空间参数无效');
 if(!Number.isFinite(g.parameters.density)||g.parameters.density<0||g.parameters.density>1)throw Error('导入的聚集强度无效');
 if(g.metadata?.space&&(!Number.isFinite(g.metadata.space.scale)||g.metadata.space.scale<=0||g.metadata.space.scale>1e5))throw Error('导入的空间基准距离无效');
 if(g.metadata?.sphere&&(!Number.isFinite(g.metadata.sphere.radius)||g.metadata.sphere.radius<=0||g.metadata.sphere.radius>1e5))throw Error('导入的球半径无效');
 g.edges.forEach(e=>{if(!e||!ids.has(e.source)||!ids.has(e.target)||e.source===e.target||!['tree','knn','wormhole'].includes(e.type))throw Error('关系边引用或类型无效');if(e.type!=='tree'&&(!Number.isFinite(e.score)||e.score< -1.00001||e.score>1.00001))throw Error('关系分数无效');if(e.type==='tree'&&ids.get(e.target).parent!==e.source)throw Error('层级边与父子结构不一致');if(e.type==='knn'&&ids.get(e.source).root!==ids.get(e.target).root)throw Error('树内近邻跨越了根主题');if(e.type==='wormhole'&&ids.get(e.source).root===ids.get(e.target).root)throw Error('虫洞须连接不同根主题')});
 const before=g.edges.length;g.edges=g.edges.filter(e=>e.type!=='wormhole'||shortWorm(ids.get(e.source).pos,ids.get(e.target).pos,g.parameters.max_worm_length,graphScale(g)));if(before>g.edges.length){g.metadata={...g.metadata,warnings:[...(g.metadata?.warnings||[]),'已移除 '+(before-g.edges.length)+' 条过长的导入虫洞。']};}
 g.map=ids;g.docs=docs;g.color=new Map(g.roots.map((id,i)=>[id,COLORS[i%COLORS.length]]));return g;
}
async function build(data){
 $('building').hidden=false;$('rebuild').disabled=true;$('cancelBuild').hidden=false;$('message').textContent='';await new Promise(r=>setTimeout(r,30));
 try{const started=performance.now(),next=prepareGraph(await computeGraph(data,parameters()));universe=next;dataset=data;selected=universe.roots[0];reset();refresh();$('message').textContent='已重建 · '+((performance.now()-started)/1000).toFixed(2)+' 秒';}
 finally{$('building').hidden=true;$('rebuild').disabled=!dataset;$('cancelBuild').hidden=true}
}
function reset(){camera.yaw=-.38;camera.pitch=.18;camera.zoom=clamp(260/(50+Math.max(80,...(universe?.nodes||[]).map(n=>Math.hypot(...n.pos)+(n.localRadius||0)))),.2,2.5);camera.focus=[0,0,0];needsDraw=true}
function refresh(){
 $('statTexts').textContent=universe.texts.length;$('statNodes').textContent=universe.nodes.filter(n=>n.kind!=='text').length;$('statWorm').textContent=universe.edges.filter(e=>e.type==='wormhole').length;$('statKnn').textContent=universe.edges.filter(e=>e.type==='knn').length;
 $('dataType').textContent='真实向量';$('sourceBadge').replaceChildren();$('sourceBadge').textContent='Rust / WASM · '+(universe.metadata?.dimension||'未知')+' 维';
 $('rootLegend').replaceChildren();universe.roots.forEach(id=>{const n=universe.map.get(id),div=document.createElement('div');div.className='legend';const dotEl=document.createElement('i');dotEl.className='dot';dotEl.style.background=universe.color.get(id);const title=document.createElement('span');title.textContent=n.label;const count=document.createElement('small');count.textContent=n.members.length;div.append(dotEl,title,count);$('rootLegend').append(div)});
 $('rebuild').disabled=!dataset;$('message').textContent=dataset?'': '已导入图谱；缺少向量，参数重建不可用。';$('workspaceStatus').textContent=(universe.metadata?.warnings||[]).join(' ');renderTree();renderDetail();needsDraw=true;
}
function renderTree(){
 const q=$('search').value.trim().toLowerCase(),box=$('tree');box.replaceChildren();let found=0;
 function row(n){const b=document.createElement('button');b.style.paddingLeft=(8+Math.min(n.depth,6)*12)+'px';b.className=n.id===selected?'selected':'';b.setAttribute('aria-label',KIND[n.kind]+'：'+n.label);const icon=document.createElement('span');icon.textContent=n.kind==='root'?'◉ ':n.kind==='text'?'· ':'◇ ';icon.style.color=universe.color.get(n.root);const count=document.createElement('span');count.className='count';count.textContent=n.kind==='text'?'':n.members.length;b.append(icon,document.createTextNode(n.label),count);b.addEventListener('click',()=>select(n.id,true));box.append(b)}
 function walk(id){const n=universe.map.get(id);if(q){if((n.label+' '+(n.kind==='text'?universe.docs.get(n.documentId)?.text:'')).toLowerCase().includes(q)&&dateMatches(n)){found++;if(found<=150)row(n)}}else if(n.kind!=='text'&&dateMatches(n))row(n);n.children.forEach(walk)}universe.roots.forEach(walk);
 $('searchCount').textContent=q?found+' 个匹配'+(found>150?'，显示前 150 个':''):'主题目录可访问所有层级；搜索可查找文本';if(!box.children.length){const e=document.createElement('p');e.className='empty';e.textContent='没有匹配的主题或文本';box.append(e)}
}
function pathOf(id){const path=[];let n=universe.map.get(id);while(n){path.unshift(n);n=universe.map.get(n.parent)}return path}
function select(id,focus=false){if(!universe.map.has(id))return;selected=id;renderTree();renderDetail();if(focus)focusSelected();needsDraw=true}
function renderDetail(){
 const n=universe.map.get(selected);if(!n)return;$('detailKind').textContent=KIND[n.kind];$('breadcrumb').textContent=pathOf(n.id).map(x=>x.label).join(' / ');$('detailTitle').textContent=n.label;
 $('detailBody').textContent=n.kind==='text'?universe.docs.get(n.documentId).text:(n.definition||'主题由真实向量聚合；名称取自代表文本，不是小 LLM 的主题判断。');
 const meta=$('detailMeta');meta.replaceChildren();function field(k,v){const d=document.createElement('div');d.className='detail-meta';const a=document.createElement('span'),b=document.createElement('span');a.textContent=k;b.textContent=v;d.append(a,b);meta.append(d)}field('节点 ID / 本次构建',n.id);field('包含文本',n.members.length);field('层级深度',n.depth);if(Number.isFinite(n.score))field('合并平均相似度',n.score.toFixed(3));if(n.kind==='text'){field('文本 ID',n.documentId);const doc=universe.docs.get(n.documentId);if(doc.date)field('原始日期',doc.date);field('来源分类',doc.category||'未标注');if(doc.inWindow===false)field('时间范围','窗口外背景');}if(Number.isFinite(n.localRadius))field('局部球半径',n.localRadius.toFixed(1));if(Number.isFinite(n.distanceToTopic))field('距最相关主题',n.distanceToTopic.toFixed(1));if(n.nearestTopic)field('最相关主题',universe.map.get(n.nearestTopic)?.label||n.nearestTopic);if(n.placement)field('空间位置',({outlier:'远离主题 · 低相关',bridge:'主题之间 · 共享关联',cluster:'主题附近 · 密集聚集',outside:'旧布局 · 球外',central:'旧布局 · 球心附近',interior:'旧布局 · 球内',surface:'旧布局 · 球面附近'})[n.placement]||n.placement);if(Number.isFinite(n.maxTopicSimilarity))field('最高叶主题相似度',n.maxTopicSimilarity.toFixed(3));if(Number.isFinite(n.scopeSimilarity))field('最高定义主题相似度',n.scopeSimilarity.toFixed(3));if(n.themeMatch)field('主题名匹配分数',n.themeMatch.toFixed(3));
 const ids=new Set([n.id]);function collect(id){const x=universe.map.get(id);ids.add(id);x.children.forEach(collect)}collect(n.id);
 const relations=universe.edges.filter(e=>e.type==='wormhole'&&(ids.has(e.source)||ids.has(e.target))).sort((a,b)=>b.score-a.score),box=$('connections');box.replaceChildren();const title=document.createElement('h3');title.className='small';title.textContent='跨树虫洞 · '+relations.length;box.append(title);
 relations.slice(0,8).forEach(e=>{const other=ids.has(e.source)?e.target:e.source,partner=universe.map.get(other),b=document.createElement('button');b.className='relation';const score=document.createElement('span');score.className='score';score.textContent=e.score.toFixed(3)+(Number.isFinite(e.lengthNormalized)?' · '+e.lengthNormalized.toFixed(2)+'D':'');b.append(score,document.createTextNode(partner.label));b.addEventListener('click',()=>select(other,true));box.append(b)});
 if(!relations.length){const p=document.createElement('p');p.className='empty';p.textContent='当前相似度、长度与限额下，没有保留跨树关系。';box.append(p)}
 if(n.kind==='text'){const doc=universe.docs.get(n.documentId),h=document.createElement('p');h.className='control-note space';h.textContent='内容与日期来自所导入的摘要，未进行独立事实核验。';box.append(h);for(const source of doc.sources||[]){try{const url=new URL(source.url);if(!['http:','https:'].includes(url.protocol))continue;const a=document.createElement('a');a.href=url.href;a.target='_blank';a.rel='noopener noreferrer';a.className='relation';a.style.color='var(--mint)';a.textContent=source.title;box.append(a)}catch{}}}
 if(n.kind!=='text'){const details=document.createElement('details');details.style.marginTop='14px';const summary=document.createElement('summary');summary.className='small';summary.textContent='查看成员文本 ('+n.members.length+')';details.append(summary);n.members.slice(0,80).forEach(id=>{const d=universe.docs.get(id),tn=universe.nodes.find(x=>x.documentId===id),b=document.createElement('button');b.className='relation';b.textContent=d.title;b.addEventListener('click',()=>{if(tn)select(tn.id,true)});details.append(b)});box.append(details)}
}
function focusSelected(){const n=universe?.map.get(selected);if(n){const wanted=n.kind==='text'?Math.max(1,n.depth-1):n.depth;if(wanted>+$('depth').value){$('depth').value=Math.min(8,wanted);$('depthOut').textContent=$('depth').value;}if(n.kind==='text')$('showTexts').checked=true;camera.focus=n.pos.slice();camera.zoom=n.kind==='text'?2.1:1.4;needsDraw=true}}
function project(pos){let [x,y,z]=pos.map((v,i)=>v-camera.focus[i]);const c=Math.cos(camera.yaw),s=Math.sin(camera.yaw);[x,z]=[x*c+z*s,-x*s+z*c];const cp=Math.cos(camera.pitch),sp=Math.sin(camera.pitch);[y,z]=[y*cp-z*sp,y*sp+z*cp];const perspective=850/Math.max(150,850+z),factor=Math.min(W/740,H/680)*camera.zoom*perspective;return {x:W/2+x*factor,y:H/2+y*factor,z,factor}}
function displayAncestor(id,visible){let n=universe.map.get(id);while(n&&!visible.has(n.id))n=universe.map.get(n.parent);return n?.id}
function draw(time){
 if(!universe||!W||!H)return;const dt=Math.min(40,time-lastTime||16);lastTime=time;
 if($('rotate').checked&&!pointers.size){camera.yaw+=dt*.00006;needsDraw=true}if(!needsDraw)return;needsDraw=false;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);
 const rnd=random(729);for(let i=0;i<100;i++){const x=rnd()*W,y=rnd()*H,r=.35+rnd()*.55;ctx.fillStyle='rgba(148,176,193,'+(.08+rnd()*.24)+')';ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}
 const depth=+$('depth').value,texts=$('showTexts').checked,visible=new Set();universe.nodes.forEach(n=>{if(dateMatches(n)&&(n.kind==='root'||(n.kind!=='text'&&n.depth<=depth)||(n.kind==='text'&&texts&&universe.map.get(n.parent).depth<=depth)))visible.add(n.id)});
 if($('showSphere').checked&&universe.metadata?.space)drawTopicSpheres(visible);
 const points=new Map();visible.forEach(id=>points.set(id,{...project(universe.map.get(id).pos),n:universe.map.get(id)}));
 const path=new Set(pathOf(selected).map(n=>n.id)),selectedNode=universe.map.get(selected),related=new Set([selected]);const selMembers=new Set(selectedNode?.members||[]);universe.nodes.forEach(n=>{if(n.kind==='text'&&selMembers.has(n.documentId))related.add(n.id)});
 const edgeSeen=new Set();drawnWorms=[];
 for(const e of universe.edges){if(e.type==='knn'&&!$('showKnn').checked)continue;if(e.type==='wormhole'&&!$('showWorm').checked)continue;let a=e.source,b=e.target;if(e.type==='wormhole'){a=displayAncestor(a,visible);b=displayAncestor(b,visible)}if(!points.has(a)||!points.has(b)||a===b)continue;const key=e.type+':'+[a,b].sort().join('|');if(edgeSeen.has(key))continue;edgeSeen.add(key);const A=points.get(a),B=points.get(b);if(e.type==='wormhole'&&!shortWorm(A.n.pos,B.n.pos,universe.parameters?.max_worm_length??.65,graphScale()))continue;const active=e.type==='tree'?path.has(a)&&path.has(b):related.has(e.source)||related.has(e.target);ctx.beginPath();ctx.moveTo(A.x,A.y);
  if(e.type==='wormhole'){drawnWorms.push({source:a,target:b,lengthNormalized:Math.hypot(...A.n.pos.map((x,i)=>x-B.n.pos[i]))/(graphScale())});ctx.lineTo(B.x,B.y);ctx.strokeStyle=active?'rgba(245,204,129,.92)':'rgba(232,191,122,.4)';ctx.lineWidth=active?1.8:1;ctx.setLineDash([5,4])}
  else{ctx.lineTo(B.x,B.y);ctx.strokeStyle=e.type==='knn'?'rgba(92,139,160,.17)':active?'rgba(187,230,218,.82)':'rgba(144,174,187,'+(universe.map.get(b).kind==='text'?.15:.34)+')';ctx.lineWidth=active?1.5:.7;ctx.setLineDash([])}ctx.stroke();
 }
 ctx.setLineDash([]);projected=[...points.values()].sort((a,b)=>b.z-a.z);let labelBoxes=[];
 for(const p of projected){const n=p.n,focus=n.id===selected,hover=n.id===hovered,color=universe.color.get(n.root),base=n.kind==='root'?9:n.kind==='branch'?4.5:n.kind==='leaf'?4:2,r=Math.max(n.kind==='text'?1.8:3,base*Math.sqrt(p.factor));p.r=r;
  if(n.kind==='root'||focus){const g=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,r*(focus?4:5));g.addColorStop(0,color+'38');g.addColorStop(1,color+'00');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,r*5,0,Math.PI*2);ctx.fill()}
  ctx.globalAlpha=n.kind==='text'&&!focus&&!hover?.65:1;ctx.fillStyle=color;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;
  if(n.kind==='root'||focus||hover){ctx.strokeStyle=focus?'#edf9f4':color+'66';ctx.lineWidth=focus?1.2:.7;ctx.beginPath();ctx.ellipse(p.x,p.y,r*1.8,r*.7,-.35,0,Math.PI*2);ctx.stroke()}
 }
 const ordered=projected.slice().sort((a,b)=>(b.n.id===selected?10:b.n.kind==='root'?8:b.n.kind==='leaf'?4:0)-(a.n.id===selected?10:a.n.kind==='root'?8:a.n.kind==='leaf'?4:0));
 for(const p of ordered){const n=p.n,focus=n.id===selected,hover=n.id===hovered;if(!(focus||hover||n.kind==='root'||n.kind==='leaf'&&camera.zoom>=.85))continue;let label=n.label.length>19?n.label.slice(0,18)+'…':n.label;ctx.font=(n.kind==='root'?'500 13px':'12px')+' system-ui, sans-serif';const width=ctx.measureText(label).width,x=clamp(p.x+p.r+8,8,W-width-8);let y=clamp(p.y+4,105,H-70),rect={x:x-4,y:y-14,w:width+8,h:19};const overlaps=box=>labelBoxes.some(r=>r.x<box.x+box.w&&r.x+r.w>box.x&&r.y<box.y+box.h&&r.y+r.h>box.y);if(n.kind==='root'){for(const offset of[0,22,-22,44,-44,66,-66,88,-88,110,-110,132,-132,154,-154]){const yy=clamp(p.y+4+offset,105,H-70),candidate={x:x-4,y:yy-14,w:width+8,h:19};if(!overlaps(candidate)){y=yy;rect=candidate;break}}if(Math.abs(y-p.y)>18){ctx.strokeStyle=colorFor(n)+'66';ctx.lineWidth=.6;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(x,y-5);ctx.stroke();}}else if(!focus&&!hover&&overlaps(rect))continue;labelBoxes.push(rect);ctx.fillStyle='#0b1422ce';ctx.fillRect(rect.x,rect.y,rect.w,rect.h);ctx.fillStyle=focus?'#eaf8f3':n.kind==='root'?colorFor(n):'#b6c4ce';ctx.fillText(label,x,y)}
}
function drawTopicSpheres(visible){
 for(const n of universe.nodes){if(n.kind==='text'||!visible.has(n.id)||!n.localRadius)continue;
  const radius=n.localRadius,origin=project(n.pos),r=radius*origin.factor,color=colorFor(n),emphasis=n.id===selected||n.kind==='root';
  if(emphasis){const fog=ctx.createRadialGradient(origin.x,origin.y,0,origin.x,origin.y,r);fog.addColorStop(0,color+'14');fog.addColorStop(1,color+'02');ctx.fillStyle=fog;ctx.beginPath();ctx.arc(origin.x,origin.y,r,0,Math.PI*2);ctx.fill();}
  const trace=get=>{let previous=project(get(0));for(let j=1;j<=48;j++){const p=project(get(j/48*Math.PI*2));ctx.beginPath();ctx.moveTo(previous.x,previous.y);ctx.lineTo(p.x,p.y);const back=(p.z+previous.z)/2>origin.z;ctx.strokeStyle=color+(emphasis?(back?'32':'80'):(back?'0d':'28'));ctx.lineWidth=emphasis?.8:.5;ctx.stroke();previous=p;}};
  for(let axis=0;axis<3;axis++)trace(t=>n.pos.map((x,i)=>x+(i===axis?0:radius*(i===(axis+1)%3?Math.cos(t):Math.sin(t)))));
 }
}
function colorFor(n){return universe.color.get(n.root)}
function resize(){const r=canvas.getBoundingClientRect();W=r.width;H=r.height;dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);needsDraw=true}
new ResizeObserver(resize).observe(canvas);
function hit(x,y){let best=null,distance=Infinity;for(const p of projected){const d=Math.hypot(p.x-x,p.y-y),threshold=p.n.kind==='text'?9:14;if(d<Math.max(threshold,p.r+5)&&d<distance){best=p;distance=d}}return best}
function mousePoint(e){const rect=canvas.getBoundingClientRect();return {x:e.clientX-rect.left,y:e.clientY-rect.top}}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{...mousePoint(e),initial:mousePoint(e)});dragMoved=false;$('hover').style.display='none';if(pointers.size===2){const p=[...pointers.values()];pinchLast=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)}});
canvas.addEventListener('pointermove',e=>{const p=mousePoint(e),old=pointers.get(e.pointerId);if(old){if(Math.hypot(p.x-old.initial.x,p.y-old.initial.y)>5)dragMoved=true;pointers.set(e.pointerId,{...p,initial:old.initial});if(pointers.size===2){const a=[...pointers.values()],dist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(pinchLast>0)camera.zoom=clamp(camera.zoom*dist/pinchLast,.3,4);pinchLast=dist;dragMoved=true}else{camera.yaw+=(p.x-old.x)*.007;camera.pitch=clamp(camera.pitch+(p.y-old.y)*.006,-1.4,1.4)}needsDraw=true;return}const h=hit(p.x,p.y);if(hovered!==h?.n.id){hovered=h?.n.id;needsDraw=true}if(h){$('hover').textContent=KIND[h.n.kind]+' · '+h.n.label;$('hover').style.display='block';$('hover').style.left=clamp(p.x+14,8,W-235)+'px';$('hover').style.top=clamp(p.y+15,8,H-70)+'px'}else $('hover').style.display='none'});
canvas.addEventListener('pointerup',e=>{const p=mousePoint(e),single=pointers.size===1;pointers.delete(e.pointerId);if(!dragMoved&&single){const h=hit(p.x,p.y);if(h)select(h.n.id)}if(pointers.size===1){const [id,v]=[...pointers.entries()][0];pointers.set(id,{...v,initial:{x:v.x,y:v.y}})}pinchLast=0});
canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);pinchLast=0});canvas.addEventListener('pointerleave',()=>{$('hover').style.display='none';hovered=null;needsDraw=true});
canvas.addEventListener('wheel',e=>{e.preventDefault();camera.zoom=clamp(camera.zoom*Math.exp(-e.deltaY*.001),.3,4);needsDraw=true},{passive:false});
canvas.addEventListener('keydown',e=>{let handled=true;if(e.key==='ArrowLeft')camera.yaw-=.1;else if(e.key==='ArrowRight')camera.yaw+=.1;else if(e.key==='ArrowUp')camera.pitch=clamp(camera.pitch-.1,-1.4,1.4);else if(e.key==='ArrowDown')camera.pitch=clamp(camera.pitch+.1,-1.4,1.4);else if(e.key==='+'||e.key==='=')camera.zoom=clamp(camera.zoom*1.1,.3,4);else if(e.key==='-')camera.zoom=clamp(camera.zoom/1.1,.3,4);else handled=false;if(handled){e.preventDefault();needsDraw=true}});
function animate(t){draw(t);requestAnimationFrame(animate)}requestAnimationFrame(animate);
[['kRoots','kOut',false],['tauIn','tauOut',true],['tauCross','crossOut',true],['knn','knnOut',false],['maxWorm','wormOut',false],['minCluster','minOut',false],['wormLength','lengthOut',true],['relevanceFloor','relevanceOut',true],['density','densityOut',true],['depth','depthOut',false]].forEach(([id,out,decimal])=>{$(id).addEventListener('input',()=>{$(out).textContent=decimal?(+$(id).value).toFixed(2):$(id).value;if(id==='depth')needsDraw=true;else $('message').textContent='参数已更改，点击重建应用。'})});
['showTexts','showWorm','showKnn','showSphere','rotate'].forEach(id=>$(id).addEventListener('change',()=>needsDraw=true));
$('rebuild').addEventListener('click',()=>{if(dataset)build(dataset).catch(e=>{$('message').textContent=e.message})});$('search').addEventListener('input',renderTree);$('zoomIn').onclick=()=>{camera.zoom=clamp(camera.zoom*1.2,.3,4);needsDraw=true};$('zoomOut').onclick=()=>{camera.zoom=clamp(camera.zoom/1.2,.3,4);needsDraw=true};$('resetView').onclick=reset;$('focusBtn').onclick=focusSelected;
function tab(show){$('explore').hidden=show;$('scheme').hidden=!show;$('mapTab').classList.toggle('active',!show);$('schemeTab').classList.toggle('active',show);$('mapTab').setAttribute('aria-selected',!show);$('schemeTab').setAttribute('aria-selected',show);if(!show){resize();needsDraw=true}}
$('mapTab').onclick=()=>tab(false);$('schemeTab').onclick=()=>tab(true);
function budget(){const N=clamp(Math.floor(+$('budgetN').value||1),1,10000000),d=+$('budgetD').value,b=+$('budgetType').value,k=clamp(Math.floor(+$('budgetK').value||0),0,1000),s=+$('budgetScore').value;const format=v=>v>=1e9?(v/1e9).toFixed(2)+' GB':(v/1e6).toFixed(2)+' MB';$('budgetDense').textContent=format(N*N*4);$('budgetVec').textContent=format(N*d*b);$('budgetGraph').textContent=N*k>4294967295?'需要 u64 偏移':format(N*k*(4+s)+(N+1)*4)}['budgetN','budgetD','budgetType','budgetK','budgetScore'].forEach(id=>$(id).addEventListener('input',budget));budget();
function modal(show){$('importModal').hidden=!show;if(show){previousFocus=document.activeElement;$('importError').textContent='';$('closeImport').focus()}else previousFocus?.focus()}
$('importBtn').onclick=()=>modal(true);$('closeImport').onclick=()=>modal(false);$('importModal').addEventListener('click',e=>{if(e.target===$('importModal'))modal(false)});document.addEventListener('keydown',e=>{if($('importModal').hidden)return;if(e.key==='Escape')modal(false);if(e.key==='Tab'){const els=[...$('importModal').querySelectorAll('button,input,textarea')].filter(e=>!e.disabled),first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
async function readNpy(file){
 if(file.size>30*1024*1024)throw Error('NPY 文件超过 30 MB');const buffer=await file.arrayBuffer(),view=new DataView(buffer),bytes=new Uint8Array(buffer);if(bytes.length<10||bytes[0]!==147||String.fromCharCode(...bytes.slice(1,6))!=='NUMPY')throw Error('不是有效的 NPY 文件');const major=bytes[6];if(![1,2,3].includes(major))throw Error('不支持此 NPY 版本');if(bytes.length<(major===1?10:12))throw Error('NPY 文件头截断');const length=major===1?view.getUint16(8,true):view.getUint32(8,true),start=major===1?10:12;if(start+length>bytes.length)throw Error('NPY 文件头越界');const header=new TextDecoder().decode(bytes.slice(start,start+length)),dtype=header.match(/['"]descr['"]\s*:\s*['"]([^'"]+)['"]/)?.[1],shape=header.match(/['"]shape['"]\s*:\s*\(([^)]*)\)/)?.[1].split(',').map(x=>x.trim()).filter(Boolean).map(Number),fortran=/['"]fortran_order['"]\s*:\s*True/.test(header);
 if(!['<f4','<f8','=f4','=f8'].includes(dtype))throw Error('NPY 仅支持 little-endian FP32 / FP64');if(!shape||shape.length!==2||shape.some(x=>!Number.isInteger(x)||x<1))throw Error('NPY 必须是二维数组');const [n,d]=shape;if(n<2||n>400||d<2||d>4096)throw Error('NPY 尺寸超出 2–400 行、2–4096 维的构建范围');const width=dtype.endsWith('4')?4:8,offset=start+length;if(offset+n*d*width!==buffer.byteLength)throw Error('NPY 数据长度与 shape 不一致');return Array.from({length:n},(_,i)=>Array.from({length:d},(_,j)=>{const off=offset+(fortran?j*n+i:i*d+j)*width;return width===4?view.getFloat32(off,true):view.getFloat64(off,true)}));
}
function setParameters(p){if(!p||typeof p!=='object')return;const fields={k_roots:'kRoots',tau_in:'tauIn',tau_cross:'tauCross',knn:'knn',max_wormholes:'maxWorm',min_cluster_size:'minCluster',max_worm_length:'wormLength',relevance_floor:'relevanceFloor',density:'density'};for(const [key,id]of Object.entries(fields)){if(Number.isFinite(p[key])){$(id).value=clamp(p[key],+$(id).min,+$(id).max);$(id).dispatchEvent(new Event('input'))}}}
$('doImport').onclick=async()=>{
 $('importError').textContent='';$('doImport').disabled=true;
 try{let text=$('jsonPaste').value.trim();if(!text){const file=$('jsonFile').files[0];if(!file)throw Error('请选择 JSON 文件或粘贴 JSON');if(file.size>40*1024*1024)throw Error('JSON 文件超过 40 MB');text=await file.text()}if(text.length>40*1024*1024)throw Error('JSON 内容过大');const raw=JSON.parse(text),npy=$('npyFile').files[0];
  if(raw.nodes&&raw.roots){if(raw.schema!=='semantic-cosmos/v1')throw Error('图谱版本须为 semantic-cosmos/v1');const next=prepareGraph(raw);let nextData=null;if(raw.vectors&&raw.texts.length<=400)nextData=datasetFrom({texts:raw.texts,vectors:raw.vectors,model:raw.metadata?.model,themes:raw.themes,themeVectors:raw.themeVectors,embedding:raw.metadata?.embedding,meta:raw.metadata?.sourceMeta});universe=next;dataset=nextData;setParameters(next.parameters);selected=universe.roots[0];reset();refresh()}
  else{const vectors=npy?await readNpy(npy):null;let data;if(vectors||raw.vectors)data=datasetFrom(raw,vectors||raw.vectors);else{const normalized=normalizeTexts(raw);data=await embedRecords(normalized,$('modelDevice').value,progress=>{$('importError').textContent=progress})}await build(data)}
  $('search').value='';renderTree();modal(false);tab(false);
 }catch(e){$('importError').textContent=e instanceof SyntaxError?'JSON 语法不正确，请检查逗号与引号。':e.message}finally{$('doImport').disabled=false}
};
$('demoBtn').onclick=async()=>{try{setParameters(DEFAULT_PARAMETERS);await build(window.COSMOS_DATA);$('search').value='';renderTree();modal(false);tab(false)}catch(e){$('importError').textContent=e.message}};
$('exportBtn').onclick=()=>{if(!universe)return;const clean={schema:universe.schema,metadata:universe.metadata,parameters:universe.parameters,roots:universe.roots,texts:universe.texts,nodes:universe.nodes.map(({memberIndices,...n})=>n),edges:universe.edges,vectors:universe.vectors,themes:universe.themes,themeVectors:universe.themeVectors};const url=URL.createObjectURL(new Blob([JSON.stringify(clean,null,2)],{type:'application/json;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='universe.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);$('message').textContent='已导出图谱、原文、参数与可用向量；可再次导入。'};

function dateMatches(n){return $('dateFilter').value!=='window'||n.members.some(id=>universe.docs.get(id)?.inWindow!==false);}
$('dateFilter').onchange=()=>{renderTree();needsDraw=true;};
$('cancelBuild').onclick=()=>{cancelJobs();$('message').textContent='已取消；保留上一次成功构建。';};
$('saveWorkspace').onclick=async()=>{try{await saveWorkspace(exportableUniverse());const persistent=await requestPersistence();$('workspaceStatus').textContent='已保存到本地浏览器。'+(persistent?'已获得持久存储。':'建议同时导出 JSON 作为备份。');}catch(e){$('workspaceStatus').textContent='保存失败：'+e.message;}};
$('loadWorkspace').onclick=async()=>{try{const raw=await loadWorkspace();if(!raw)throw Error('还没有本地快照');const next=prepareGraph(raw);let nextData=null;if(raw.vectors)nextData=datasetFrom({texts:raw.texts,vectors:raw.vectors,model:raw.metadata?.model,themes:raw.themes,themeVectors:raw.themeVectors,embedding:raw.metadata?.embedding,meta:raw.metadata?.sourceMeta});universe=next;dataset=nextData;selected=raw.roots[0];setParameters(next.parameters);reset();refresh();$('workspaceStatus').textContent='已恢复本地工作区。';}catch(e){$('workspaceStatus').textContent='恢复失败：'+e.message;}};
$('reembedBtn').onclick=async()=>{if(!dataset)return;$('reembedBtn').disabled=true;$('cancelBuild').hidden=false;try{const next=await embedRecords({records:dataset.records,themes:dataset.themes||[],sourceMeta:dataset.sourceMeta||{},warnings:dataset.warnings||[]},$('modelDevice').value,progress=>{$('message').textContent=progress});await build(next);}catch(e){$('message').textContent=e.message;}finally{$('reembedBtn').disabled=false;$('cancelBuild').hidden=true;}};
function exportableUniverse(){const {map,docs,color,...clean}=universe;return {...clean,nodes:clean.nodes.map(({memberIndices,...n})=>n)};}
window.cosmosDebug={get graph(){return universe;},get data(){return dataset;},get camera(){return camera;},get projected(){return projected;},get drawnWorms(){return drawnWorms;},computeGraph,exportableUniverse,readNpy};
if(location.protocol!=='file:'&&'serviceWorker' in navigator){navigator.serviceWorker.register(new URL('../sw.js',import.meta.url),{scope:new URL('../',import.meta.url).pathname}).catch(()=>{});}

build(window.COSMOS_DATA).catch(e=>{$('message').textContent='构建失败：'+e.message});
