import {adaptDocument} from './local-import.js';
import {setupLocalImport} from './local-import-ui.js';
import {parseSource,connectSource,readSourceFile,DEFAULT_DRIVE} from './sources.js';
import {dot,unit,clamp,random} from './core.js';
import {SceneView} from './scene-view.js';
import {ROLE_LABEL} from './presentation.js';
import {openCatalog} from './catalog.js';
import {SPACE_SCALE,shortWorm} from './space.js';
import {datasetFrom,normalizeTexts,MODEL_ID,DEFAULT_PARAMETERS} from './adapters.js';
import {computeGraph,embedRecords,cancelJobs} from './workers-client.js';
import {saveWorkspace,loadWorkspace,requestPersistence} from './storage.js';
import {INFERENCE_RUNTIME} from './inference-config.js';
import {OrbitalDisplay} from './orbits.js';

const $=id=>document.getElementById(id);
function parameters(){return {k_roots:+$('kRoots').value,tau_in:+$('tauIn').value,tau_cross:+$('tauCross').value,knn:+$('knn').value,max_wormholes:+$('maxWorm').value,min_cluster_size:+$('minCluster').value,max_worm_length:+$('wormLength').value,relevance_floor:+$('relevanceFloor').value,density:+$('density').value}}
const COLORS=['#9be4ce','#80bde8','#e8bf7a','#b3a6ee','#e89ca5','#9fcea0','#cdbaa5','#90c8d5'];
const KIND={root:'星系',branch:'主题区域',leaf:'恒星系',text:'行星 · 资料'};
let catalog=null, matchSet=null, cardObject=null,treeTapTimer=null;
let dataset=null, universe=null, selected=null, hovered=null, projected=[], needsDraw=true, previousFocus=null,drawnWorms=[];
const camera={yaw:-.38,pitch:.18,zoom:1,focus:[0,0,0]};
let lastDrawDuration=0;
let orbital=null,orbitLastDraw=0,drawCount=0,followSelected=false,drawnOrbits=[];
const motionPreference=matchMedia('(prefers-reduced-motion: reduce)');
function moving(){return $('orbitEnabled').checked&&!orbital?.clock.paused&&!document.hidden;}
function motionPosition(n){return orbital?orbital.position(n,$('orbitEnabled').checked):n.pos;}
function readingPause(){if(!orbital)return;orbital.reading($('orbitReading').checked&&!$('nodeCard').hidden?universe.map.get(selected):null);needsDraw=true;}
let W=0,H=0,dpr=1,lastTime=0,pinchLast=0,dragMoved=false;
const canvas=$('cosmos'),ctx=canvas.getContext('2d'),pointers=new Map();
const view=new SceneView({canvas,camera,getClock:()=>orbital?.clock,matchNode:n=>dateMatches(n),consumeDirty:()=>{const dirty=needsDraw;needsDraw=false;return dirty;},onCard:openCard,onCloseCard:closeCard,onError:message=>$('message').textContent=message,onScene:()=>{renderTree();needsDraw=true;}});
function graphScale(g=universe){return g?.metadata?.space?.scale??g?.metadata?.sphere?.radius??SPACE_SCALE;}
function prepareGraph(g){
 if(!g||!Array.isArray(g.nodes)||!Array.isArray(g.edges)||!Array.isArray(g.roots)||!Array.isArray(g.texts))throw Error('图谱需要 roots、nodes、edges 与 texts 数组');
 if(!g.nodes.length||g.nodes.length>40000||g.edges.length>400000)throw Error('图谱支持 1–40000 节点、最多 400000 条边');
 const ids=new Map();g.nodes.forEach(n=>{if(!n||typeof n.id!=='string'||!n.id||ids.has(n.id))throw Error('图谱节点 ID 缺失或重复');if(!KIND[n.kind]||typeof n.label!=='string')throw Error('节点类型或名称无效');if(!Array.isArray(n.pos)||n.pos.length!==3||n.pos.some(x=>!Number.isFinite(x)||Math.abs(x)>1e7))throw Error('节点坐标无效');if(n.localRadius!==undefined&&(!Number.isFinite(n.localRadius)||n.localRadius<=0||n.localRadius>1e5))throw Error('主题邻域半径无效');if(!Array.isArray(n.children)||!Array.isArray(n.members))throw Error('节点缺少 children 或 members');if(!Number.isInteger(n.depth)||n.depth<0||n.depth>100)throw Error('节点层级无效');ids.set(n.id,n)});
 const rootSet=new Set(g.roots);if(rootSet.size!==g.roots.length||!rootSet.size)throw Error('根主题为空或重复');g.roots.forEach(id=>{const n=ids.get(id);if(!n||n.kind!=='root'||n.parent!==null||n.root!==id||n.depth!==0)throw Error('根主题引用无效')});
 g.nodes.forEach(n=>{if(!rootSet.has(n.root))throw Error('节点根主题不存在');if(n.kind==='root'&&!rootSet.has(n.id))throw Error('根节点未在 roots 中声明');if(n.kind!=='root'){const parent=ids.get(n.parent);if(!parent||parent.root!==n.root||parent.depth+1!==n.depth||!parent.children.includes(n.id))throw Error('父子层级或根归属不一致')}if(new Set(n.children).size!==n.children.length)throw Error('重复子节点');n.children.forEach(id=>{if(!ids.has(id)||ids.get(id).parent!==n.id)throw Error('子节点引用不一致')});if(n.kind==='text'&&n.children.length)throw Error('文本节点不能有子节点')});
 const visited=new Set();function visit(id){if(visited.has(id))throw Error('图谱包含循环或多重父节点');visited.add(id);ids.get(id).children.forEach(visit)}g.roots.forEach(visit);if(visited.size!==ids.size)throw Error('图谱存在未连接节点');
 const docs=new Map();g.texts.forEach(t=>{if(!t||typeof t.id!=='string'||docs.has(t.id)||typeof t.text!=='string'||typeof t.title!=='string')throw Error('图谱文本格式错误或 ID 重复');docs.set(t.id,t)});g.nodes.forEach(n=>{if(n.members.some(id=>!docs.has(id))||new Set(n.members).size!==n.members.length)throw Error('节点成员文本不存在或重复');if(n.kind==='text'&&(!docs.has(n.documentId)||n.members.length!==1||n.members[0]!==n.documentId))throw Error('文本节点缺少有效 documentId')});
 g.parameters={...DEFAULT_PARAMETERS,...g.parameters};
 if(!Number.isFinite(g.parameters.max_worm_length)||g.parameters.max_worm_length<.1||g.parameters.max_worm_length>1.5||!Number.isFinite(g.parameters.relevance_floor)||g.parameters.relevance_floor<0||g.parameters.relevance_floor>.95)throw Error('导入的空间参数无效');
 if(!Number.isFinite(g.parameters.density)||g.parameters.density<0||g.parameters.density>1)throw Error('导入的聚集强度无效');
 if(g.metadata?.space&&(!Number.isFinite(g.metadata.space.scale)||g.metadata.space.scale<=0||g.metadata.space.scale>1e5))throw Error('导入的空间基准距离无效');
 if(g.metadata?.sphere&&(!Number.isFinite(g.metadata.sphere.radius)||g.metadata.sphere.radius<=0||g.metadata.sphere.radius>1e5))throw Error('导入的球半径无效');
 g.edges.forEach(e=>{if(!e||!ids.has(e.source)||!ids.has(e.target)||e.source===e.target||!['tree','knn','wormhole'].includes(e.type))throw Error('关系边引用或类型无效');if(e.type!=='tree'&&(!Number.isFinite(e.score)||e.score< -1.00001||e.score>1.00001))throw Error('关系分数无效');if(e.type==='tree'&&ids.get(e.target).parent!==e.source)throw Error('层级边与父子结构不一致');if(e.type==='knn'&&ids.get(e.source).root!==ids.get(e.target).root)throw Error('树内近邻跨越了根主题');if(e.type==='wormhole'&&ids.get(e.source).root===ids.get(e.target).root)throw Error('虫洞须连接不同根主题')});
 const before=g.edges.length;g.edges=g.edges.filter(e=>e.type!=='wormhole'||shortWorm(ids.get(e.source).pos,ids.get(e.target).pos,g.parameters.max_worm_length,graphScale(g)));if(before>g.edges.length){g.metadata={...g.metadata,warnings:[...(g.metadata?.warnings||[]),'已移除 '+(before-g.edges.length)+' 条过长的导入虫洞。']};}
 g.map=ids;g.docs=docs;g.docNodes=new Map(g.nodes.filter(n=>n.kind==='text').map(n=>[n.documentId,n.id]));g.adjacency=new Map();for(const e of g.edges)indexEdge(g,e);g.color=new Map(g.roots.map((id,i)=>[id,COLORS[i%COLORS.length]]));return g;
}
function indexEdge(g,e){for(const id of [e.source,e.target]){if(!g.adjacency.has(id))g.adjacency.set(id,[]);g.adjacency.get(id).push(e);}}
async function hydrate(){if(catalog){dataset=await catalog.hydrate();$('rebuild').disabled=false;}return dataset;}
async function defaultData(){if(window.COSMOS_DATA)return window.COSMOS_DATA;return await (await fetch('./data/news-halfyear-vectors.json')).json();}
async function build(data,checkCurrent=()=>{}){
 $('building').hidden=false;$('rebuild').disabled=true;$('cancelBuild').hidden=false;$('message').textContent='';await new Promise(r=>setTimeout(r,30));
 try{const started=performance.now(),computed=await computeGraph(data,parameters());checkCurrent();const next=prepareGraph(computed);catalog=null;matchSet=null;universe=next;dataset=data;selected=universe.roots[0];reset();refresh();$('message').textContent='已重建 · '+((performance.now()-started)/1000).toFixed(2)+' 秒';}
 finally{$('building').hidden=true;$('rebuild').disabled=!dataset;$('cancelBuild').hidden=true}
}
function reset(){followSelected=false;camera.yaw=-.38;camera.pitch=.18;camera.zoom=clamp(260/(50+Math.max(80,...(universe?.nodes||[]).map(n=>Math.hypot(...n.pos)+(n.localRadius||0)))),.2,2.5);camera.focus=[0,0,0];needsDraw=true}
function refresh(){
 if(orbital?.graph!==universe){orbital=new OrbitalDisplay(universe);orbitLastDraw=0;followSelected=false;closeCard();syncMotion();view.initialize(universe,catalog);readingPause();}
 const hierarchical=!!universe.metadata?.hierarchy;for(const id of ['kRoots','tauIn','tauCross','maxWorm','minCluster','wormLength','relevanceFloor'])$(id).disabled=hierarchical;
 $('statTexts').textContent=universe.texts.length;$('statNodes').textContent=universe.nodes.filter(n=>n.kind!=='text').length;$('statWorm').textContent=catalog?(universe.metadata?.edgeCounts?.wormhole??0):universe.edges.filter(e=>e.type==='wormhole').length;$('statKnn').textContent=catalog?(universe.metadata?.edgeCounts?.knn??0):universe.edges.filter(e=>e.type==='knn').length;
 matchSet=null;updateMatches();$('dataType').textContent=universe.metadata?.sourceMeta?.synthetic?'合成压力数据':'真实向量';$('sourceBadge').replaceChildren();$('sourceBadge').textContent=(universe.metadata?.hierarchy?'分层宇宙':'Rust / WASM')+' · '+(universe.metadata?.dimension||'未知')+' 维';
 const embeddingBackend=universe.metadata?.embedding?.backend;if(embeddingBackend){$('sourceBadge').append(document.createElement('br'),document.createTextNode('嵌入：'+(embeddingBackend==='webgpu'?'WebGPU':'WASM / CPU')));}
 $('rootLegend').replaceChildren();universe.roots.forEach(id=>{const n=universe.map.get(id),div=document.createElement('div');div.className='legend';const dotEl=document.createElement('i');dotEl.className='dot';dotEl.style.background=universe.color.get(id);const title=document.createElement('span');title.textContent=n.label;const count=document.createElement('small');count.textContent=n.members.length;div.append(dotEl,title,count);$('rootLegend').append(div)});
 $('rebuild').disabled=!dataset&&!catalog;$('message').textContent=catalog?'目录已就绪 · 详情和来源按需加载':dataset?'': '已导入图谱；缺少向量，参数重建不可用。';$('workspaceStatus').textContent=(universe.metadata?.warnings||[]).join(' ');if(embeddingBackend==='webgpu'&&universe.metadata?.embedding?.runtime!==INFERENCE_RUNTIME)$('workspaceStatus').textContent+=' 此图使用旧 WebGPU 推理运行时；请重新嵌入以修复布局。';renderTree();renderDetail();needsDraw=true;
}
function renderTree(){
 clearTimeout(treeTapTimer);const q=$('search').value.trim().toLowerCase(),box=$('tree');box.replaceChildren();if(!view.nav)return;let found=0;
 const row=(display,search=false)=>{const n=universe.map.get(display.semanticId),b=document.createElement('button');b.className=n?.id===selected?'selected':'';b.setAttribute('aria-label',ROLE_LABEL[display.role]+'：'+display.label);b.textContent=display.label+(display.role==='planet'?'':'  · '+display.count);b.onclick=()=>{clearTimeout(treeTapTimer);if(search)select(display.semanticId,true);else treeTapTimer=setTimeout(()=>openCard(display),270);};b.ondblclick=()=>{clearTimeout(treeTapTimer);if(!search){closeCard();view.enter(display);}};box.append(b);};
 if(q){for(const doc of universe.texts){const n=universe.map.get(universe.docNodes.get(doc.id));if(!dateMatches(n)||![doc.title,doc.text,doc.vendor,doc.model_name,doc.topic,doc.evidence_category].join(' ').toLowerCase().includes(q))continue;found++;if(found<=150)row({semanticId:n.id,role:'planet',label:n.label,count:1,documentId:n.documentId},true);}}
 else{for(const n of view.nodes()){found++;row(n);}}
 $('searchCount').textContent=q?found+' 条匹配'+(found>150?'；显示前 150 条':''):'当前范围的下一层；单击看卡片，双击进入';if(!box.children.length){const e=document.createElement('p');e.className='empty';e.textContent='没有匹配资料';box.append(e);}needsDraw=true;
}
function pathOf(id){const path=[];let n=universe.map.get(id);while(n){path.unshift(n);n=universe.map.get(n.parent)}return path}
async function select(id,focus=false){if(!universe.map.has(id))return;const graph=universe;if(focus&&!await view.navigateTo(id))return;if(graph!==universe)return;const n=universe.map.get(id),display=view.nodeFor(id)||{id:'planet:'+id,semanticId:id,documentId:n.documentId,role:n.kind==='text'?'planet':n.kind==='leaf'?'system':n.kind==='root'?'galaxy':'region',label:n.label,count:n.members.length,scopeId:view.presentation.semanticScopes[id]};openCard(display);}
function openCard(node){cardObject=node;view.selectedNodeId=node.id;selected=node.semanticId||selected;$('nodeCard').hidden=false;renderDetail();readingPause();$('enterCard').hidden=!node.scopeId||node.scopeId===view.nav?.active;$('enterCard').onclick=()=>{closeCard();view.enter(node);};needsDraw=true;if(catalog&&node.semanticId)catalog.ensure(node.semanticId).then(()=>{if(cardObject?.id===node.id&&!$('nodeCard').hidden){view.enableSources(node,universe.docs.get(universe.map.get(node.semanticId)?.documentId));$('enterCard').hidden=!node.scopeId||node.scopeId===view.nav.active;renderDetail();}needsDraw=true;}).catch(e=>$('message').textContent=e.message);}
function closeCard(){$('nodeCard').hidden=true;cardObject=null;view.selectedNodeId=null;readingPause();needsDraw=true;}
function renderRangeCard(){const node=cardObject;if(!node)return;const scope=view.presentation.scopes[node.scopeId||view.nav.active];$('detailKind').textContent=ROLE_LABEL[node.role];$('detailTitle').textContent=node.label;$('breadcrumb').textContent=view.nav.path().map(s=>ROLE_LABEL[s.role]+' · '+s.label).join(' / ');$('detailBody').textContent=node.role==='region'?'有软边界的主题范围。内部恒星系可属于此区域，星云不作为统一公转中心。':'这个范围聚合相关资料；只展示当前范围与下一层预览。';$('detailMeta').replaceChildren();for(const [k,v]of [['资料数量',node.count??scope?.count??universe.texts.length],['下一层预览',scope?.childCount??0],['浏览方式','双击或对准放大进入；缩远返回父范围']]){const d=document.createElement('div');d.className='detail-meta';d.textContent=k+'：'+v;$('detailMeta').append(d);}$('connections').replaceChildren();}
function renderDetail(){
 if(cardObject&& !['planet','source'].includes(cardObject.role)){renderRangeCard();return;}
 const n=universe.map.get(selected);if(!n)return;$('detailKind').textContent=cardObject?ROLE_LABEL[cardObject.role]:KIND[n.kind];$('breadcrumb').textContent=(view.presentation?.routes[n.id]||[]).map(id=>view.presentation.scopes[id]?.label||id).join(' / ');$('detailTitle').textContent=cardObject?.role==='source'?cardObject.label:n.label;
 $('detailBody').textContent=n.kind==='text'?universe.docs.get(n.documentId).text:(n.definition||'主题由真实向量聚合；名称取自代表文本，不是小 LLM 的主题判断。');
 const meta=$('detailMeta');meta.replaceChildren();function field(k,v){const d=document.createElement('div');d.className='detail-meta';const a=document.createElement('span'),b=document.createElement('span');a.textContent=k;b.textContent=v;d.append(a,b);meta.append(d)}field('节点 ID / 本次构建',n.id);field('包含文本',n.members.length);field('层级深度',n.depth);if(Number.isFinite(n.score))field('合并平均相似度',n.score.toFixed(3));if(n.kind==='text'){field('文本 ID',n.documentId);const doc=universe.docs.get(n.documentId);if(doc.import_provenance){field('本地文件',doc.import_provenance.file);field('原始 ID',doc.original_id??'无原 ID，使用内容指纹');field('原始行号',doc.import_provenance.indices.map(i=>i+1).join(', '));const fileInfo=universe.metadata?.sourceMeta?.local_import?.files?.find(f=>f.path===doc.import_provenance.file);if(fileInfo?.metadata?.license_note)field('许可说明',fileInfo.metadata.license_note);}if(doc.generated_at)field('日报生成时间',doc.generated_at);if(doc.authors?.length)field('作者',doc.authors.join(', '));field('事件日期',doc.event_date||(doc.date_basis==='published'?null:doc.date)||'日期未确认');field('发布日期',doc.published_date||doc.published||'日期未确认');field('证据类别',doc.evidence_category||'未证实观点');if(doc.vendor)field('厂商 / 模型',doc.vendor+' / '+(doc.model_name||''));if(doc.limitations)field('证据局限',doc.limitations);if(cardObject?.role==='source'){const source=(doc.sources||[]).find(s=>s.url===cardObject.sourceURL);field('来源证据类别',source?.evidence_category||doc.evidence_category||'未证实观点');field('来源 URL',cardObject.sourceURL);}field('来源分类',doc.category||'未标注');if(doc.inWindow===false)field('时间范围','窗口外背景');}if(Number.isFinite(n.localRadius))field('局部球半径',n.localRadius.toFixed(1));if(Number.isFinite(n.distanceToTopic))field('距最相关主题',n.distanceToTopic.toFixed(1));if(n.nearestTopic)field('最相关主题',universe.map.get(n.nearestTopic)?.label||n.nearestTopic);if(n.placement)field('空间位置',({outlier:'远离主题 · 低相关',bridge:'主题之间 · 共享关联',cluster:'主题附近 · 密集聚集',outside:'旧布局 · 球外',central:'旧布局 · 球心附近',interior:'旧布局 · 球内',surface:'旧布局 · 球面附近'})[n.placement]||n.placement);if(Number.isFinite(n.maxTopicSimilarity))field('最高叶主题相似度',n.maxTopicSimilarity.toFixed(3));if(Number.isFinite(n.scopeSimilarity))field('最高定义主题相似度',n.scopeSimilarity.toFixed(3));if(n.themeMatch)field('主题名匹配分数',n.themeMatch.toFixed(3));
 const ids=new Set([n.id]);function collect(id){const x=universe.map.get(id);ids.add(id);x.children.forEach(collect)}collect(n.id);
 const relations=[...new Set([...ids].flatMap(id=>universe.adjacency.get(id)||[]))].filter(e=>e.type==='wormhole').sort((a,b)=>b.score-a.score),box=$('connections');box.replaceChildren();const title=document.createElement('h3');title.className='small';title.textContent='跨树虫洞 · '+relations.length;box.append(title);
 relations.slice(0,8).forEach(e=>{const other=ids.has(e.source)?e.target:e.source,partner=universe.map.get(other),b=document.createElement('button');b.className='relation';const score=document.createElement('span');score.className='score';score.textContent=e.score.toFixed(3)+(Number.isFinite(e.lengthNormalized)?' · '+e.lengthNormalized.toFixed(2)+'D':'');b.append(score,document.createTextNode(partner.label));b.addEventListener('click',()=>select(other,true));box.append(b)});
 if(!relations.length){const p=document.createElement('p');p.className='empty';p.textContent='当前相似度、长度与限额下，没有保留跨树关系。';box.append(p)}
 if(n.kind==='text'){const doc=universe.docs.get(n.documentId),h=document.createElement('p');h.className='control-note space';h.textContent=doc.pending?'来源加载中…':doc.verification_status==='official-search-excerpt'?'仅核对官方搜索摘要；未完整读取正文，请结合证据局限。':doc.verification_status==='source-read'?'已对照所列来源；官方声明、独立测试与用户报告保留各自的证据边界。':'原始记录 / 未独立核验；不得据此推断整体故障率。';box.append(h);for(const source of doc.sources||[]){try{const url=new URL(source.url);if(!['http:','https:'].includes(url.protocol))continue;const a=document.createElement('a');a.href=url.href;a.target='_blank';a.rel='noopener noreferrer';a.className='relation';a.style.color='var(--mint)';a.textContent='☾ 来源卫星 · '+source.title+' · '+(source.evidence_category||doc.evidence_category||'未证实观点');box.append(a)}catch{}}}
 if(n.kind!=='text'){const details=document.createElement('details');details.style.marginTop='14px';const summary=document.createElement('summary');summary.className='small';summary.textContent='查看成员文本 ('+n.members.length+')';details.append(summary);n.members.slice(0,80).forEach(id=>{const d=universe.docs.get(id),tn=universe.map.get(universe.docNodes.get(id)),b=document.createElement('button');b.className='relation';b.textContent=d.title;b.addEventListener('click',()=>{if(tn)select(tn.id,true)});details.append(b)});box.append(details)}
}
async function focusSelected(){if(selected)await view.navigateTo(selected);}
function project(pos){return view.project(pos);}
function resize(){view.resize();}
function syncMotion(){if(orbital){orbital.clock.tick(performance.now());orbital.clock.paused=!$('orbitEnabled').checked||$('orbitPause').getAttribute('aria-pressed')==='true';orbital.clock.speed=+$('orbitSpeed').value;orbital.clock.sync();}needsDraw=true;$('orbitStatus').textContent=!$('orbitEnabled').checked?'静态视图 · 语义数据不变':$('orbitPause').getAttribute('aria-pressed')==='true'?'全局暂停':'近景展开轨道 · 阅读时局部暂停';}
$('orbitEnabled').checked=!motionPreference.matches;$('orbitEnabled').onchange=syncMotion;$('orbitTrails').onchange=()=>needsDraw=true;
$('orbitSpeed').oninput=()=>{$('orbitSpeedOut').textContent=(+$('orbitSpeed').value).toFixed(2)+'×';syncMotion();};
$('orbitPause').onclick=()=>{const paused=$('orbitPause').getAttribute('aria-pressed')!=='true';$('orbitPause').setAttribute('aria-pressed',String(paused));$('orbitPause').textContent=paused?'恢复运动':'暂停运动';syncMotion();};$('orbitReset').onclick=()=>{orbital?.clock.reset();needsDraw=true;};$('orbitReading').onchange=()=>{readingPause();syncMotion();};
motionPreference.addEventListener('change',e=>{if(e.matches){$('orbitEnabled').checked=false;$('rotate').checked=false;syncMotion();}});
for(const event of ['visibilitychange','freeze','resume'])document.addEventListener(event,()=>{if(orbital){orbital.clock.tick(performance.now());orbital.clock.hidden=event==='freeze'||document.hidden;orbital.clock.sync();}needsDraw=true;});
$('closeCard').onclick=closeCard;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('nodeCard').hidden)closeCard();});
$('sceneBack').onclick=()=>view.exit();$('sceneHome').onclick=()=>view.home();$('scenePrev').onclick=()=>{view.page=Math.max(0,view.page-1);renderTree();};$('sceneNext').onclick=()=>{view.page++;renderTree();};
[['kRoots','kOut',false],['tauIn','tauOut',true],['tauCross','crossOut',true],['knn','knnOut',false],['maxWorm','wormOut',false],['minCluster','minOut',false],['wormLength','lengthOut',true],['relevanceFloor','relevanceOut',true],['density','densityOut',true],['depth','depthOut',false]].forEach(([id,out,decimal])=>{$(id).addEventListener('input',()=>{$(out).textContent=decimal?(+$(id).value).toFixed(2):$(id).value;if(id==='depth')needsDraw=true;else $('message').textContent='参数已更改，点击重建应用。'})});
['showTexts','showWorm','showKnn','showSphere','rotate'].forEach(id=>$(id).addEventListener('change',()=>needsDraw=true));
$('rebuild').addEventListener('click',()=>{hydrate().then(data=>{if(data)return build(data)}).catch(e=>{$('message').textContent=e.message})});$('search').addEventListener('input',renderTree);$('zoomIn').onclick=()=>view.zoom(1.25);$('zoomOut').onclick=()=>view.zoom(.8);$('resetView').onclick=()=>view.fit();$('focusBtn').onclick=focusSelected;
function tab(show){$('explore').hidden=show;$('scheme').hidden=!show;$('mapTab').classList.toggle('active',!show);$('schemeTab').classList.toggle('active',show);$('mapTab').setAttribute('aria-selected',!show);$('schemeTab').setAttribute('aria-selected',show);if(!show){resize();needsDraw=true}}
$('mapTab').onclick=()=>tab(false);$('schemeTab').onclick=()=>tab(true);
function budget(){const N=clamp(Math.floor(+$('budgetN').value||1),1,10000000),d=+$('budgetD').value,b=+$('budgetType').value,k=clamp(Math.floor(+$('budgetK').value||0),0,1000),s=+$('budgetScore').value;const format=v=>v>=1e9?(v/1e9).toFixed(2)+' GB':(v/1e6).toFixed(2)+' MB';$('budgetDense').textContent=format(N*N*4);$('budgetVec').textContent=format(N*d*b);$('budgetGraph').textContent=N*k>4294967295?'需要 u64 偏移':format(N*k*(4+s)+(N+1)*4)}['budgetN','budgetD','budgetType','budgetK','budgetScore'].forEach(id=>$(id).addEventListener('input',budget));budget();
function modal(show){$('importModal').hidden=!show;if(show){previousFocus=document.activeElement;$('importError').textContent='';$('closeImport').focus()}else previousFocus?.focus()}
$('importBtn').onclick=()=>modal(true);$('closeImport').onclick=()=>modal(false);$('importModal').addEventListener('click',e=>{if(e.target===$('importModal'))modal(false)});document.addEventListener('keydown',e=>{if($('importModal').hidden)return;if(e.key==='Escape')modal(false);if(e.key==='Tab'){const els=[...$('importModal').querySelectorAll('button,input,textarea')].filter(e=>!e.disabled),first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
async function readNpy(file){
 if(file.size>30*1024*1024)throw Error('NPY 文件超过 30 MB');const buffer=await file.arrayBuffer(),view=new DataView(buffer),bytes=new Uint8Array(buffer);if(bytes.length<10||bytes[0]!==147||String.fromCharCode(...bytes.slice(1,6))!=='NUMPY')throw Error('不是有效的 NPY 文件');const major=bytes[6];if(![1,2,3].includes(major))throw Error('不支持此 NPY 版本');if(bytes.length<(major===1?10:12))throw Error('NPY 文件头截断');const length=major===1?view.getUint16(8,true):view.getUint32(8,true),start=major===1?10:12;if(start+length>bytes.length)throw Error('NPY 文件头越界');const header=new TextDecoder().decode(bytes.slice(start,start+length)),dtype=header.match(/['"]descr['"]\s*:\s*['"]([^'"]+)['"]/)?.[1],shape=header.match(/['"]shape['"]\s*:\s*\(([^)]*)\)/)?.[1].split(',').map(x=>x.trim()).filter(Boolean).map(Number),fortran=/['"]fortran_order['"]\s*:\s*True/.test(header);
 if(!['<f4','<f8','=f4','=f8'].includes(dtype))throw Error('NPY 仅支持 little-endian FP32 / FP64');if(!shape||shape.length!==2||shape.some(x=>!Number.isInteger(x)||x<1))throw Error('NPY 必须是二维数组');const [n,d]=shape;if(n<1||n>20000||d<2||d>4096||n*d>10240000)throw Error('NPY 尺寸超出 1–20000 行、2–4096 维和 1024 万数值的构建范围');const width=dtype.endsWith('4')?4:8,offset=start+length;if(offset+n*d*width!==buffer.byteLength)throw Error('NPY 数据长度与 shape 不一致');return Array.from({length:n},(_,i)=>Array.from({length:d},(_,j)=>{const off=offset+(fortran?j*n+i:i*d+j)*width;return width===4?view.getFloat32(off,true):view.getFloat64(off,true)}));
}
function setParameters(p){if(!p||typeof p!=='object')return;const fields={k_roots:'kRoots',tau_in:'tauIn',tau_cross:'tauCross',knn:'knn',max_wormholes:'maxWorm',min_cluster_size:'minCluster',max_worm_length:'wormLength',relevance_floor:'relevanceFloor',density:'density'};for(const [key,id]of Object.entries(fields)){if(Number.isFinite(p[key])){$(id).value=clamp(p[key],+$(id).min,+$(id).max);$(id).dispatchEvent(new Event('input'))}}}
let sourceConnection=null,sourceGeneration=0,importVersion=0;
const localImport=setupLocalImport($,{onCancelImport:()=>{importVersion++;cancelJobs();},validateGraph:prepareGraph});
const sourceLinks={github:'https://github.com/StarrySky7D4/semantic-cosmos',drive:DEFAULT_DRIVE};
function invalidateSource(){sourceConnection=null;sourceGeneration++;$('sourceFiles').replaceChildren();$('sourceFiles').hidden=true;$('sourceStatus').textContent='';}
$('sourceType').onchange=()=>{importVersion++;cancelJobs();invalidateSource();localImport.sourceChanged();const kind=$('sourceType').value;$('remoteSource').hidden=kind!=='github';$('folderSource').hidden=kind!=='folder';$('driveSource').hidden=kind!=='drive';$('sourceLink').value=sourceLinks[kind]||'';$('sourceRef').disabled=kind!=='github';$('jsonFile').disabled=kind!=='local';$('jsonPaste').disabled=kind!=='local';$('npyFile').disabled=kind!=='local';if(kind!=='folder')$('doImport').disabled=kind==='drive';};
$('driveToLocal').onclick=()=>{$('sourceType').value='folder';$('sourceType').dispatchEvent(new Event('change'));};
$('sourceLink').oninput=()=>{sourceLinks[$('sourceType').value]=$('sourceLink').value;invalidateSource();};$('sourceRef').oninput=invalidateSource;
$('connectSource').onclick=async()=>{invalidateSource();const generation=sourceGeneration;$('connectSource').disabled=true;$('sourceStatus').textContent='正在验证来源…';try{const result=await connectSource(parseSource($('sourceType').value,$('sourceLink').value),{ref:$('sourceRef').value});if(generation!==sourceGeneration)return;sourceConnection=result;for(const [i,file]of result.files.entries()){const option=document.createElement('option');option.value=i;option.textContent=file.name;$('sourceFiles').append(option)}$('sourceFiles').hidden=false;$('sourceStatus').textContent=result.label;}catch(e){if(generation===sourceGeneration)$('sourceStatus').textContent=e.message;}finally{$('connectSource').disabled=false;}};
$('doImport').onclick=async()=>{
 $('importError').textContent='';$('doImport').disabled=true;const version=++importVersion;const checkCurrent=()=>{if(version!==importVersion)throw Error('已取消导入，原有图谱未改变。');};
 const importControls=['sourceType','sourceLink','sourceRef','sourceFiles','connectSource','jsonFile','jsonPaste','npyFile','demoBtn','folderFiles','multiFiles','previewLocal','driveToLocal'].map(id=>[$(id),$(id).disabled]).concat([...$('localFileList').querySelectorAll('input')].map(el=>[el,el.disabled]));for(const [el]of importControls)el.disabled=true;
 try{let raw,npy=null;if($('sourceType').value==='local'){let text=$('jsonPaste').value.trim();if(!text){const file=$('jsonFile').files[0];if(!file)throw Error('请选择 JSON 文件或粘贴 JSON');if(file.size>40*1024*1024)throw Error('JSON 文件超过 40 MB');text=await file.text()}if(new TextEncoder().encode(text).length>40*1024*1024)throw Error('JSON 数据超过 40 MB');raw=JSON.parse(text);npy=$('npyFile').files[0];}else if($('sourceType').value==='folder'){raw=localImport.raw;}else if($('sourceType').value==='drive'){throw Error('请自行下载到本地后导入。');}else{if(!sourceConnection)throw Error('请先验证连接并选择 JSON 文件。');const generation=sourceGeneration;$('importError').textContent='正在读取并验证 JSON…';raw=await readSourceFile(sourceConnection.files[+$('sourceFiles').value]);if(generation!==sourceGeneration)throw Error('来源设置已变化，请重新读取。');}
  checkCurrent();if(!(raw.nodes&&raw.roots)){const adapted=adaptDocument(raw);if(adapted.format==='manifest')throw Error('这是文件清单，请选择清单对应的 JSON 文件，或使用本地文件夹导入。');raw={...(!Array.isArray(raw)?raw:{}),texts:adapted.records,items:undefined,records:undefined,meta:adapted.meta};}
  if(raw.nodes&&raw.roots){if(raw.schema!=='semantic-cosmos/v1')throw Error('图谱版本须为 semantic-cosmos/v1');const next=prepareGraph(raw);let nextData=null;if(raw.vectors&&raw.texts.length<=20000)nextData=datasetFrom({texts:raw.texts,vectors:raw.vectors,model:raw.metadata?.model,themes:raw.themes,themeVectors:raw.themeVectors,embedding:raw.metadata?.embedding,meta:raw.metadata?.sourceMeta});catalog=null;matchSet=null;universe=next;dataset=nextData;setParameters(next.parameters);selected=universe.roots[0];reset();refresh()}
  else{const vectors=npy?await readNpy(npy):null;let data;if(vectors||raw.vectors)data=datasetFrom(raw,vectors||raw.vectors);else{const normalized=normalizeTexts(raw);data=await embedRecords(normalized,$('modelDevice').value,progress=>{$('importError').textContent=progress},{progressTimeout:$('sourceType').value==='folder'&&normalized.records.length>400})}checkCurrent();await build(data,checkCurrent)}
  $('search').value='';renderTree();$('importError').textContent='';modal(false);tab(false);
 }catch(e){$('importError').textContent=e instanceof SyntaxError?'JSON 语法不正确，请检查逗号与引号。':e.message}finally{$('doImport').disabled=false;for(const [el,disabled]of importControls)el.disabled=disabled;if($('sourceType').value==='folder')localImport.sourceChanged();}
};
$('demoBtn').onclick=async()=>{try{setParameters(DEFAULT_PARAMETERS);await build(await defaultData());$('search').value='';renderTree();modal(false);tab(false)}catch(e){$('importError').textContent=e.message}};
$('exportBtn').onclick=async()=>{if(!universe)return;try{await hydrate();const clean={schema:universe.schema,metadata:universe.metadata,parameters:universe.parameters,roots:universe.roots,texts:universe.texts,nodes:universe.nodes.map(({memberIndices,...n})=>n),edges:universe.edges,vectors:universe.vectors,themes:universe.themes,themeVectors:universe.themeVectors};const url=URL.createObjectURL(new Blob([JSON.stringify(clean,null,2)],{type:'application/json;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='universe.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);$('message').textContent='已导出图谱、原文、参数与可用向量；可再次导入。'}catch(e){$('message').textContent=e.message;}};

function updateMatches(){if(!universe)return;const date=$('dateFilter').value,evidence=$('evidenceFilter').value,vendor=$('vendorFilter').value;matchSet=new Set();for(const doc of universe.texts){if(date==='window'&&doc.inWindow!==true||evidence&&doc.evidence_category!==evidence||vendor&&!doc.vendor?.includes(vendor))continue;let n=universe.map.get(universe.docNodes.get(doc.id));while(n&&!matchSet.has(n.id)){matchSet.add(n.id);n=universe.map.get(n.parent);}}}
function dateMatches(n){return !matchSet||matchSet.has(n.id);}
for(const id of ['dateFilter','evidenceFilter','vendorFilter'])$(id).onchange=()=>{updateMatches();renderTree();needsDraw=true;};
$('cancelBuild').onclick=()=>{cancelJobs();$('message').textContent='已取消；保留上一次成功构建。';};
$('saveWorkspace').onclick=async()=>{try{await hydrate();await saveWorkspace(exportableUniverse());const persistent=await requestPersistence();$('workspaceStatus').textContent='已保存到本地浏览器。'+(persistent?'已获得持久存储。':'建议同时导出 JSON 作为备份。');}catch(e){$('workspaceStatus').textContent='保存失败：'+e.message;}};
$('loadWorkspace').onclick=async()=>{try{const raw=await loadWorkspace();if(!raw)throw Error('还没有本地快照');const next=prepareGraph(raw);let nextData=null;if(raw.vectors)nextData=datasetFrom({texts:raw.texts,vectors:raw.vectors,model:raw.metadata?.model,themes:raw.themes,themeVectors:raw.themeVectors,embedding:raw.metadata?.embedding,meta:raw.metadata?.sourceMeta});catalog=null;matchSet=null;universe=next;dataset=nextData;selected=raw.roots[0];setParameters(next.parameters);reset();refresh();$('workspaceStatus').textContent='已恢复本地工作区。';}catch(e){$('workspaceStatus').textContent='恢复失败：'+e.message;}};
$('reembedBtn').onclick=async()=>{if($('reembedBtn').disabled)return;$('reembedBtn').disabled=true;try{await hydrate();if(!dataset)return;$('cancelBuild').hidden=false;const next=await embedRecords({records:dataset.records,themes:dataset.themes||[],sourceMeta:dataset.sourceMeta||{},warnings:dataset.warnings||[]},$('modelDevice').value,progress=>{$('message').textContent=progress});await build(next);}catch(e){$('message').textContent=e.message;}finally{$('reembedBtn').disabled=false;$('cancelBuild').hidden=true;}};
function exportableUniverse(){const {map,docs,color,docNodes,adjacency,...clean}=universe;return {...clean,nodes:clean.nodes.map(({memberIndices,...n})=>n)};}
window.cosmosDebug={get localPreview(){return localImport.preview;},get graph(){return universe;},get data(){return dataset;},get camera(){return camera;},get projected(){return view.projected;},get drawnWorms(){return view.drawnWorms;},get orbital(){return orbital;},get drawnOrbits(){return view.drawnOrbits;},get view(){return view;},project,computeGraph,embedRecords,hydrate,select,exportableUniverse,readNpy,get loadedChunks(){return catalog?.loadedChunks||0;},get selected(){return selected;},get counters(){return {visible:view.projected.length,nodes:universe?.nodes.length,drawDurationMs:view.lastDrawDuration,drawCount:view.drawCount,orbitTime:orbital?.clock.time,orbitDefinitions:view.orbitCache.size};}};
if(location.protocol!=='file:'&&'serviceWorker' in navigator){navigator.serviceWorker.register(new URL('../sw.js',import.meta.url),{scope:new URL('../',import.meta.url).pathname}).catch(()=>{});}

async function start(){if(window.COSMOS_CATALOG){const loader=openCatalog(window.COSMOS_CATALOG,e=>{if(universe!==loader.graph)return;if(e)indexEdge(universe,e);needsDraw=true;});catalog=loader;universe=prepareGraph(catalog.graph);selected=universe.roots[0];reset();refresh();}else if(window.COSMOS_GRAPH){universe=prepareGraph(window.COSMOS_GRAPH);dataset=window.COSMOS_DATA;selected=universe.roots[0];reset();refresh();}else await build(window.COSMOS_DATA);}
start().catch(e=>{$('message').textContent='加载失败：'+e.message});
