// The catalogue contains aggregate geometry and a linear search index. Document
// geometry, original records, sources and neighbour edges are fetched in shards.
export function openCatalog(manifest,onChange=()=>{}){
 const graph={...manifest.graph,texts:manifest.index.map(x=>({...x.record,pending:true})),nodes:manifest.graph.nodes.map(n=>({...n,children:n.children.slice()})),edges:manifest.graph.edges.slice()},chunks=new Map(),jobs=[];let active=0,fullData;
 const sceneJobs=new Map();
 const index=new Map(manifest.index.map(x=>[x.record.id,x])),topics=new Map(graph.nodes.map(n=>[n.id,n]));
 for(const x of manifest.index){const parent=topics.get(x.parent);graph.nodes.push({id:x.nodeId,kind:'text',label:x.record.title,members:[x.record.id],children:[],documentId:x.record.id,parent:x.parent,root:parent.root,depth:parent.depth+1,pos:parent.pos.slice(),pending:true});}
 const offsets=new Map(graph.nodes.map((n,i)=>[n.id,i])),textOffsets=new Map(graph.texts.map((t,i)=>[t.id,i]));
 function drain(){while(active<4&&jobs.length){active++;jobs.shift()().finally(()=>{active--;drain()});}}
 function load(key){if(chunks.has(key))return chunks.get(key);const promise=new Promise((resolve,reject)=>{jobs.push(async()=>{try{const response=await fetch(new URL('data/chunks/'+key+'.json',new URL('../',import.meta.url)));if(!response.ok)throw Error('资料分片读取失败：'+response.status);const shard=await response.json();for(const n of shard.nodes){graph.nodes[offsets.get(n.id)]=n;graph.map?.set(n.id,n);}for(const t of shard.texts){graph.texts[textOffsets.get(t.id)]=t;graph.docs?.set(t.id,t);}for(const e of shard.edges){graph.edges.push(e);onChange(e);}resolve();onChange();}catch(e){chunks.delete(key);reject(e);}});drain();});chunks.set(key,promise);return promise;}
 return {graph,presentation:manifest.presentation,async loadScene(id){if(sceneJobs.has(id))return sceneJobs.get(id);const scope=manifest.presentation?.scopes[id];if(!scope)throw Error('场景不存在');const promise=fetch(new URL('data/scenes/'+scope.chunk+'.json',new URL('../',import.meta.url))).then(r=>{if(!r.ok)throw Error('场景加载失败：'+r.status);return r.json();}).catch(e=>{sceneJobs.delete(id);throw e;});sceneJobs.set(id,promise);return promise;},ensure(id){const x=index.get(graph.map?.get(id)?.documentId);return x?load(x.chunk):Promise.resolve();},async hydrate(){await Promise.all([...new Set(manifest.index.map(x=>x.chunk))].map(load));if(!fullData){const r=await fetch(new URL(manifest.vectors,new URL('../',import.meta.url)));if(!r.ok)throw Error('向量读取失败：'+r.status);fullData=await r.json();}if(fullData.records.length!==graph.texts.length||fullData.records.some((r,i)=>r.id!==graph.texts[i].id))throw Error('目录与向量 ID 顺序不一致');graph.vectors=fullData.vectors;graph.themeVectors=fullData.themeVectors;graph.metadata.embedding=fullData.embedding;return fullData;},get loadedScenes(){return sceneJobs.size;},get loadedChunks(){return chunks.size;}};
}
