// The semantic forest is immutable input. Celestial roles and scene coordinates
// belong to this separate presentation, not to the embedding or exported graph.
export const ROLE_LABEL={universe:'宇宙',galaxy:'星系',region:'星云 / 主题区域',system:'恒星系',planet:'行星 · 事件',source:'来源卫星'};
const hash=s=>{let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0;};
const length=p=>Math.hypot(...p),sub=(a,b)=>a.map((x,i)=>x-b[i]);
function arrange(items){if(!items.length)return items;if(items.every(n=>n.role==='galaxy')&&items.length>1)return items.map((n,i)=>{const z=1-2*(i+.5)/items.length,a=i*Math.PI*(3-Math.sqrt(5)),r=Math.sqrt(1-z*z)*68;return {...n,pos:[Math.cos(a)*r,z*68,Math.sin(a)*r]};});const center=[0,1,2].map(a=>items.reduce((s,n)=>s+n.semanticPos[a],0)/items.length),extent=Math.max(1,...items.map(n=>length(sub(n.semanticPos,center)))),occupied=new Set();return items.map((n,i)=>{let pos=sub(n.semanticPos,center).map(x=>x/extent*65);const key=p=>p.map(x=>Math.round(x/15)).join(',');if(occupied.has(key(pos))||items.length>1&&extent<=1){const phase=hash(n.id)/4294967296*Math.PI*2,z=(i+.5)/items.length*2-1,r=Math.sqrt(1-z*z)*58;pos=[Math.cos(phase)*r,z*58,Math.sin(phase)*r];}occupied.add(key(pos));return {...n,pos};});}
export function buildPresentation(graph){
 const map=graph.map||new Map(graph.nodes.map(n=>[n.id,n])),docs=graph.docs||new Map(graph.texts.map(d=>[d.id,d])),scopes={},scenes={},routes={},semanticScopes={},regionForSystem=new Map();
 const usedChunks=new Set();const add=(id,role,parent,semanticId,label,root,count)=>{let chunk=role+'-'+hash(id).toString(16)+'-'+hash('scope|'+id).toString(16);while(usedChunks.has(chunk))chunk+='x';usedChunks.add(chunk);scopes[id]={id,role,parent,semanticId,label,root,count,chunk};scenes[id]={id,role,parent,label,root,radius:100,children:[]};if(semanticId)semanticScopes[semanticId]=id;return scopes[id];};
 add('universe','universe',null,null,'语义宇宙',null,graph.texts.length);
 const leavesUnder=id=>{const result=[],queue=[id];while(queue.length){const n=map.get(queue.pop());if(n.kind==='leaf')result.push(n);else if(n.kind!=='text')queue.push(...n.children);}return result.sort((a,b)=>a.id.localeCompare(b.id));};
 for(const rootId of graph.roots){const root=map.get(rootId),galaxyId='galaxy:'+rootId;add(galaxyId,'galaxy','universe',rootId,root.label,rootId,root.members.length);scenes.universe.children.push({id:galaxyId,scopeId:galaxyId,semanticId:rootId,role:'galaxy',label:root.label,root:rootId,count:root.members.length,semanticPos:root.pos,radius:23});
  const systems=leavesUnder(rootId),field=systems.length>3?systems.slice().sort((a,b)=>length(sub(b.pos,root.pos))-length(sub(a.pos,root.pos))||a.id.localeCompare(b.id))[0]:null,assigned=new Set();
  if(systems.length>3)for(const branchId of root.children){const branch=map.get(branchId),members=leavesUnder(branchId).filter(n=>n.id!==field?.id);if(members.length<2)continue;const id='region:'+branchId,count=members.reduce((s,n)=>s+n.members.length,0);add(id,'region',galaxyId,branchId,branch.label,rootId,count);scenes[galaxyId].children.push({id,scopeId:id,semanticId:branchId,role:'region',label:branch.label,root:rootId,count,semanticPos:branch.pos,radius:26,lobes:[{pos:[-7,2,-3],radius:19},{pos:[8,-3,4],radius:18},{pos:[0,7,1],radius:15}]});for(const system of members){regionForSystem.set(system.id,id);assigned.add(system.id);}}
  for(const system of systems){const id='system:'+system.id,parent=regionForSystem.get(system.id)||galaxyId;add(id,'system',parent,system.id,system.label,rootId,system.members.length);scenes[parent].children.push({id,scopeId:id,semanticId:system.id,role:'system',label:system.label,root:rootId,count:system.members.length,semanticPos:system.pos,radius:10});
   for(const docId of system.children){const n=map.get(docId),doc=docs.get(n.documentId),id='planet:'+docId,sources=(doc.sources||[]).filter(s=>/^https?:\/\//.test(s.url)).slice(0,6),scopeId=sources.length?id:null;scenes['system:'+system.id].children.push({id,scopeId,semanticId:n.id,documentId:n.documentId,role:'planet',label:n.label,root:rootId,count:1,semanticPos:n.pos,radius:8,systemId:system.id});
    if(scopeId){add(id,'planet','system:'+system.id,n.id,n.label,rootId,1);scenes[id].systemId=system.id;scenes[id].documentId=n.documentId;scenes[id].children=sources.map((s,i)=>({id:'source:'+docId+':'+i,scopeId:null,semanticId:n.id,documentId:n.documentId,role:'source',label:s.title,sourceURL:s.url,sourceIndex:i,root:rootId,count:1,pos:[0,0,0],radius:3,systemId:system.id}));}
    const route=['universe',galaxyId];if(parent!==galaxyId)route.push(parent);route.push('system:'+system.id);routes[n.id]=route;routes[n.documentId]=route;
   }
  }
 }
 for(const scene of Object.values(scenes))if(scene.role!=='planet')scene.children=arrange(scene.children);
 for(const scene of Object.values(scenes)){scene.children=scene.children.map(({semanticPos,...n})=>n);const scope=scopes[scene.id];scope.childCount=scene.children.length;scope.children=scene.children.filter(n=>n.scopeId).map(n=>n.scopeId);if(scope.semanticId&&!routes[scope.semanticId]){const chain=[];let s=scope;while(s){chain.unshift(s.id);s=scopes[s.parent];}routes[scope.semanticId]=chain;}}
 return {version:1,root:'universe',scopes,routes,semanticScopes,scenes};
}
export function compactPresentation(p){return {version:p.version,root:p.root,scopes:p.scopes,routes:p.routes,semanticScopes:p.semanticScopes,overview:p.scenes.universe};}
