import {SceneNavigator} from './scene.js';
import {buildPresentation,ROLE_LABEL} from './presentation.js';
import {sceneOrbit,at,frame as orbitFrame} from './orbits.js';
import {representatives,expandsAdjacent} from './two-layers.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),$=id=>document.getElementById(id),copy=c=>({...c,focus:c.focus.slice()}),mix=(a,b,t)=>a+(b-a)*t;
export class SceneView{
 constructor(options){Object.assign(this,options);this.ctx=this.canvas.getContext('2d');this.W=0;this.H=0;this.dpr=1;this.projected=[];this.drawnOrbits=[];this.drawnWorms=[];this.orbitCache=new Map();this.pointers=new Map();this.drawCount=0;this.lastDrawDuration=0;this.dirty=true;this.lastDraw=0;this.transition=null;this.nav=null;this.navigationSequence=0;this.graph=null;this.page=0;this.hovered=null;this.tapTimer=null;this.lastTap=null;this.lastWheel=-Infinity;this.gestureCamera=null;
  new ResizeObserver(()=>this.resize()).observe(this.canvas);this.events();requestAnimationFrame(t=>this.loop(t));
 }
 initialize(graph,catalog){this.navigationSequence++;this.graph=graph;this.catalog=catalog;const p=catalog?.presentation||buildPresentation(graph);this.presentation=p;this.nav=new SceneNavigator(p,id=>catalog?.presentation?catalog.loadScene(id):p.scenes[id]);this.orbitCache.clear();this.previewJobs=new Map();this.previewFailed=new Set();this.projected=[];this.page=0;this.navStamp='';this.fit(false);this.updateNavigation();this.dirty=true;}
 resize(){const r=this.canvas.getBoundingClientRect();this.W=r.width;this.H=r.height;this.dpr=Math.min(2,devicePixelRatio||1);this.canvas.width=Math.round(this.W*this.dpr);this.canvas.height=Math.round(this.H*this.dpr);this.dirty=true;}
 clock(){return this.getClock?.();}
 fit(animate=true){if(!this.nav)return;const target={...this.camera,focus:this.nav.frame.origin.slice(),zoom:1.85/this.nav.frame.scale};this.moveCamera(target,animate);}
 moveCamera(target,animate=true){if(animate&&!matchMedia('(prefers-reduced-motion: reduce)').matches)this.transition={from:copy(this.camera),to:copy(target),start:performance.now(),duration:280};else{Object.assign(this.camera,copy(target));this.transition=null;}this.dirty=true;}
 orbit(node,scene=this.nav.scene){const key=scene.id+'|'+node.id;if(!this.orbitCache.has(key))this.orbitCache.set(key,sceneOrbit(node,node.systemId||scene.systemId||scene.id));return this.orbitCache.get(key);}
 localPosition(node,scene=this.nav.scene){if((node.role==='planet'||node.role==='source')&&$('orbitEnabled').checked){const id=node.systemId||scene.systemId,seconds=this.clock()?.seconds(id)||0;return at(this.orbit(node,scene),seconds);}return node.pos||[0,0,0];}
 updateFrames(){if(!this.nav)return;for(let i=1;i<this.nav.frames.length;i++){const f=this.nav.frames[i],parent=this.nav.frames[i-1],scene=this.nav.cache.get(parent.id),node=scene.children.find(n=>n.id===f.parentNodeId);if(node)f.origin=this.nav.world(this.localPosition(node,scene),parent);}}
 world(node,scene=this.nav.scene,frame=this.nav.frame){if(node.previewParentId){const parent=scene.children.find(n=>n.id===node.previewParentId),childScene=this.nav.cache.get(parent?.scopeId);if(parent&&childScene)return this.localPosition(node,childScene).map((x,i)=>this.world(parent,scene,frame)[i]+x*frame.scale*parent.radius/100);}return this.nav.world(this.localPosition(node,scene),frame);}
 project(pos){let [x,y,z]=pos.map((v,i)=>v-this.camera.focus[i]);const cy=Math.cos(this.camera.yaw),sy=Math.sin(this.camera.yaw);[x,z]=[x*cy+z*sy,-x*sy+z*cy];const cp=Math.cos(this.camera.pitch),sp=Math.sin(this.camera.pitch);[y,z]=[y*cp-z*sp,y*sp+z*cp];const factor=Math.min(this.W/740,this.H/680)*this.camera.zoom*850/Math.max(150,850+z);return{x:this.W/2+x*factor,y:this.H/2+y*factor,z,factor};}
 point(e){const r=this.canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
 budget(){return this.W<600?Math.min(80,+$('depth').value*16):Math.min(180,+$('depth').value*36);}
 primaryBudget(){return expandsAdjacent(this.nav?.scene.role)?Math.max(1,Math.floor(this.budget()*.65)):this.budget();}
 nodes(){if(!this.nav)return[];const budget=this.primaryBudget();const nodes=this.nav.scene.children.filter(n=>this.matches(n));return nodes.slice(this.page*budget,(this.page+1)*budget);}
 secondaryNodes(primary){
  if(!expandsAdjacent(this.nav.scene.role))return[];const nav=this.nav,frame=nav.frame,remaining=Math.max(0,this.budget()-primary.length),parents=primary.map(n=>({n,p:this.project(this.world(n))})).filter(({n,p})=>n.scopeId&&n.radius*frame.scale*p.factor>14&&p.x>-60&&p.x<this.W+60&&p.y>100&&p.y<this.H-45).sort((a,b)=>Number(b.n.id===this.hovered)-Number(a.n.id===this.hovered)||Math.hypot(a.p.x-this.W/2,a.p.y-this.H/2)-Math.hypot(b.p.x-this.W/2,b.p.y-this.H/2)).slice(0,8),rows=[];
  for(const {n,p}of parents){const child=nav.cache.get(n.scopeId);if(!child){if(!this.previewJobs.has(n.scopeId)&&!this.previewFailed.has(n.scopeId)&&this.previewJobs.size<4){const job=nav.ensure(n.scopeId).then(()=>{if(this.nav===nav)this.dirty=true;}).catch(e=>{this.previewFailed.add(n.scopeId);this.onError(e.message);}).finally(()=>{this.previewJobs.delete(n.scopeId);if(this.nav===nav)this.dirty=true;});this.previewJobs.set(n.scopeId,job);}continue;}const limit=Math.min(remaining-rows.length,n.id===this.hovered?6:n.radius*frame.scale*p.factor>65?4:3);if(limit<=0)break;const chosen=representatives(child.children,limit,x=>{const world=this.localPosition(x,child).map((v,i)=>this.world(n)[i]+v*frame.scale*n.radius/100),q=this.project(world);return (x.id===this.selectedNodeId?1e6:0)-Math.hypot(q.x-this.W/2,q.y-this.H/2);},x=>this.matches(x));rows.push(...chosen.map(x=>({...x,previewParentId:n.id,layer:2})));}
  return rows;
 }
 displayScale(node){const parent=node.previewParentId&&this.nav.scene.children.find(n=>n.id===node.previewParentId);return this.nav.frame.scale*(parent?parent.radius/100:1);}
 matches(n){if(n.role==='source')return true;if(n.role==='region'){const scope=this.presentation.scopes[n.scopeId];return scope.children.some(id=>{const semantic=this.graph.map.get(this.presentation.scopes[id].semanticId);return semantic&&this.matchNode(semantic);});}const semantic=this.graph.map.get(n.semanticId);return !semantic||this.matchNode(semantic);}
 nodeFor(id){return this.nav?.scene.children.find(n=>n.semanticId===id)||null;}
 enableSources(node,doc){if(node?.scopeId||node?.role!=='planet')return;const sources=(doc?.sources||[]).filter(s=>/^https?:\/\//.test(s.url)).slice(0,6);if(!sources.length)return;const id='planet:'+node.semanticId,parent=this.presentation.routes[node.semanticId]?.at(-1),systemId=this.graph.map.get(node.semanticId)?.parent,scene={id,role:'planet',parent,label:node.label,root:node.root,radius:100,systemId,documentId:doc.id,children:sources.map((s,i)=>({id:'source:'+node.semanticId+':'+i,scopeId:null,semanticId:node.semanticId,documentId:doc.id,role:'source',label:s.title,sourceURL:s.url,sourceIndex:i,root:node.root,count:1,pos:[0,0,0],radius:3,systemId}))};node.scopeId=id;this.presentation.scopes[id]={id,role:'planet',parent,label:node.label,root:node.root,semanticId:node.semanticId,count:1,childCount:sources.length,children:[]};this.nav.cache.set(id,scene);}
 async enter(node,fit=true){if(node?.previewParentId){const parent=this.nav.scene.children.find(n=>n.id===node.previewParentId);if(!parent||!await this.enter(parent,false))return false;this.fit(false);const child=this.nav.scene.children.find(n=>n.id===node.id);return child?this.enter(child,fit):false;}if(!this.nav||!node?.scopeId||node.scopeId===this.nav.active){if(node)this.onCard(node);return false;}this.cancelTap();const parentScene=this.nav.scene,parentFrame=this.nav.frame;let old;const world=()=>{const w=this.world(node,parentScene,parentFrame);old=this.project(w);return w;};try{if(!await this.nav.enter(node,this.camera,world))return false;const next=this.project(this.nav.frame.origin);this.nav.anchorError=Math.hypot(old.x-next.x,old.y-next.y);this.page=0;this.updateNavigation();this.onScene?.();if(fit)this.fit();this.dirty=true;return true;}catch(e){this.onError(e.message);return false;}}
 exit(){if(!this.nav||this.nav.frames.length===1)return false;this.cancelTap();const from=copy(this.camera);if(!this.nav.exit(this.camera))return false;const to=copy(this.camera);Object.assign(this.camera,from);this.page=0;this.moveCamera(to);this.updateNavigation();this.onScene?.();return true;}
 home(){if(!this.nav)return;this.navigationSequence++;this.nav.home(this.camera);this.page=0;this.fit();this.updateNavigation();this.onScene?.();}
 async navigateTo(id){const route=this.presentation.routes[id];if(!route)return false;const sequence=++this.navigationSequence,nav=this.nav;try{const scenes=await Promise.all(route.map(x=>nav.ensure(x)));if(sequence!==this.navigationSequence||nav!==this.nav)return false;const frames=[{id:'universe',origin:[0,0,0],scale:1}];for(let i=1;i<route.length;i++){const parent=frames[i-1],node=scenes[i-1].children.find(n=>n.scopeId===route[i]);if(!node)throw Error('检索路径缺少目标范围');const origin=node.pos.map((x,j)=>parent.origin[j]+x*parent.scale),scale=parent.scale*node.radius/100;frames.push({id:route[i],origin,scale,parentNodeId:node.id,returnCamera:{...this.camera,focus:parent.origin.slice(),zoom:1.85/parent.scale}});}this.nav.frames=frames;this.nav.scene=scenes.at(-1);this.nav.lastTransition=performance.now();const index=this.nav.scene.children.filter(n=>this.matches(n)).findIndex(n=>n.semanticId===id);this.page=Math.max(0,Math.floor(index/this.primaryBudget()));this.fit(false);this.updateNavigation();this.onScene?.();this.dirty=true;return true;}catch(e){this.onError(e.message);return false;}}
 updateNavigation(){if(!this.nav)return;const visible=this.nav.scene.children.filter(n=>this.matches(n)).length,budget=this.primaryBudget(),stamp=this.nav.active+'|'+this.page+'|'+visible+'|'+budget;if(stamp===this.navStamp)return;this.navStamp=stamp;const bar=$('sceneBreadcrumb');bar.replaceChildren();this.nav.path().forEach((s,i)=>{const b=document.createElement('button');b.textContent=s.role==='universe'?'宇宙':ROLE_LABEL[s.role]+' · '+s.label.slice(0,16);b.disabled=i===this.nav.frames.length-1;b.onclick=()=>{while(this.nav.frames.length>i+1)this.nav.exit(this.camera);this.fit();this.page=0;this.updateNavigation();this.onScene?.();};bar.append(b);});$('sceneBack').disabled=this.nav.frames.length===1;$('sceneLevel').textContent=ROLE_LABEL[this.nav.scene.role]+' / 主层与相邻层';$('scenePage').textContent=(visible?'第 '+(this.page+1)+' / '+Math.ceil(visible/budget)+' 页':'无匹配资料');$('scenePrev').disabled=this.page===0;$('sceneNext').disabled=(this.page+1)*budget>=visible;}
 range(node,world,color,emphasis=false){const radius=node.radius*this.nav.frame.scale,origin=this.project(world),lobes=node.role==='region'?(node.lobes||[{pos:[-7,2,-3],radius:19},{pos:[8,-3,4],radius:18},{pos:[0,7,1],radius:15}]):[{pos:[0,0,0],radius:node.radius}],plane=orbitFrame(node.id),screens=[];
  for(const lobe of lobes){const p=this.project(world.map((x,i)=>x+(plane.u[i]*lobe.pos[0]+plane.v[i]*lobe.pos[1]+(i===2?lobe.pos[2]:0))*this.nav.frame.scale)),r=lobe.radius*this.nav.frame.scale*p.factor;screens.push({x:p.x,y:p.y,r});const gradient=this.ctx.createRadialGradient(p.x,p.y,Math.max(0,r*.03),p.x,p.y,Math.max(.01,r));gradient.addColorStop(0,color+(emphasis?'72':'40'));gradient.addColorStop(.45,color+(emphasis?'38':'20'));gradient.addColorStop(1,color+'00');this.ctx.fillStyle=gradient;this.ctx.beginPath();this.ctx.arc(p.x,p.y,Math.max(.01,r),0,Math.PI*2);this.ctx.fill();}
  if(emphasis&&$('showSphere').checked){this.ctx.strokeStyle=color+'90';this.ctx.setLineDash([3,5]);this.ctx.lineWidth=.8;this.ctx.beginPath();this.ctx.arc(origin.x,origin.y,Math.max(1,radius*origin.factor),0,Math.PI*2);this.ctx.stroke();this.ctx.setLineDash([]);}return screens;
 }
 trace(worlds,color){this.ctx.strokeStyle=color;this.ctx.lineWidth=.65;this.ctx.beginPath();worlds.forEach((w,i)=>{const p=this.project(w);if(i)this.ctx.lineTo(p.x,p.y);else this.ctx.moveTo(p.x,p.y)});this.ctx.stroke();}
 draw(time){const start=performance.now(),ctx=this.ctx;ctx.setTransform(this.dpr,0,0,this.dpr,0,0);ctx.clearRect(0,0,this.W,this.H);for(let i=0;i<100;i++){const x=((i*7919+131)%10007)/10007*this.W,y=((i*5431+27)%9973)/9973*this.H;ctx.fillStyle='#9ab6c322';ctx.fillRect(x,y,i%3===0?1.2:.7,i%3===0?1.2:.7);}
  const scene=this.nav.scene,frame=this.nav.frame,origin=this.project(frame.origin),color=this.graph.color.get(scene.root)||'#9be4ce',current={id:scene.id,scopeId:scene.id,semanticId:this.presentation.scopes[scene.id]?.semanticId,role:scene.role,label:scene.label,root:scene.root,radius:100,count:this.presentation.scopes[scene.id]?.count};
  let contextLobes=null;if(scene.role==='region'||scene.role==='galaxy')contextLobes=this.range({...current,lobes:scene.role==='region'?[{pos:[-26,8,-11],radius:73},{pos:[30,-11,15],radius:69},{pos:[0,26,4],radius:58}]:null},frame.origin,color,false);
  if(scene.role==='system'||scene.role==='planet'){const r=scene.role==='system'?12:19,g=ctx.createRadialGradient(origin.x,origin.y,0,origin.x,origin.y,r*3);g.addColorStop(0,color+'aa');g.addColorStop(1,color+'00');ctx.fillStyle=g;ctx.beginPath();ctx.arc(origin.x,origin.y,r*3,0,Math.PI*2);ctx.fill();ctx.fillStyle=scene.role==='system'?'#ffe5a8':color;ctx.beginPath();ctx.arc(origin.x,origin.y,r,0,Math.PI*2);ctx.fill();ctx.font='12px system-ui';ctx.fillStyle=color;ctx.fillText(ROLE_LABEL[scene.role],origin.x+r+8,origin.y-8);}
  this.contextPoint={...origin,world:frame.origin.slice(),node:current,r:scene.role==='system'?12:scene.role==='planet'?19:100*frame.scale*origin.factor,lobes:contextLobes};const primary=this.nodes(),nodes=[...primary.map(n=>({...n,layer:1})),...this.secondaryNodes(primary)],points=[],trails=[];this.layerCounts={primary:primary.length,secondary:nodes.length-primary.length,budget:this.budget()};this.drawnWorms=[];this.drawnOrbits=[];
  for(const n of nodes){if(n.role==='planet'&&!$('showTexts').checked)continue;const world=this.world(n),p={...this.project(world),world,node:n,n:{...n,id:n.semanticId||n.id,viewId:n.id,kind:n.role==='planet'?'text':n.role==='source'?'satellite':n.role==='system'?'leaf':n.role==='region'?'branch':'root'}},c=this.graph.color.get(n.root)||'#9be4ce';p.layer=n.layer;p.r=n.role==='system'?(n.layer===2?3.5:5):n.role==='planet'?(n.layer===2?3:5):n.role==='source'?4:Math.max(4,n.radius*this.displayScale(n)*p.factor);if(n.role==='region'||n.role==='galaxy')p.lobes=this.range({...n,radius:n.radius*(n.previewParentId?this.displayScale(n)/frame.scale:1),lobes:n.lobes?.map(l=>({...l,pos:l.pos.map(x=>x*(n.previewParentId?this.displayScale(n)/frame.scale:1)),radius:l.radius*(n.previewParentId?this.displayScale(n)/frame.scale:1)}))},world,c,n.id===this.hovered);
   else{if((n.role==='planet'||n.role==='source')&&$('orbitEnabled').checked&&$('orbitTrails').checked){const parent=n.previewParentId&&scene.children.find(x=>x.id===n.previewParentId),childScene=parent?this.nav.cache.get(parent.scopeId):scene,o=this.orbit(n,childScene);if(trails.length<(this.W<600?12:32)){this.trace(o.trail.map(x=>n.previewParentId?x.map((v,i)=>this.world(parent)[i]+v*this.displayScale(n)):this.nav.world(x)),c+(n.layer===2?'20':'35'));trails.push(n.id);this.drawnOrbits.push({id:n.id,normal:o.normal});}}if(n.role==='system'){ctx.fillStyle=c+(n.layer===2?'40':'65');ctx.beginPath();ctx.arc(p.x,p.y,p.r*2,0,Math.PI*2);ctx.fill();}ctx.fillStyle=n.role==='source'?'#efd6a0':n.role==='system'?'#ffe6b4':c;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();if(n.id===this.hovered||n.id===this.selectedNodeId){ctx.strokeStyle='#f0fff4';ctx.lineWidth=1;ctx.beginPath();ctx.arc(p.x,p.y,p.r+4,0,Math.PI*2);ctx.stroke();}}
   p.n={...this.graph.map.get(n.semanticId),...p.n};points.push(p);
  }
  const labels=[];for(const p of points.slice().sort((a,b)=>(a.layer||1)-(b.layer||1)||b.z-a.z)){if(p.x<0||p.x>this.W||p.y<120||p.y>this.H-55)continue;const n=p.node,range=n.role==='region'||n.role==='galaxy',label=n.label.length>(range?12:20)?n.label.slice(0,range?11:19)+'…':n.label;ctx.font=range?(n.layer===2?'11px system-ui':'500 13px system-ui'):(n.layer===2?'10px system-ui':'12px system-ui');const x=range?p.x-ctx.measureText(label).width/2:p.x+p.r+7,y=range?p.y+p.r*.55:p.y+4,box={x:x-3,y:y-13,w:ctx.measureText(label).width+6,h:range?35:18};if(labels.some(b=>b.y<box.y+box.h&&b.y+b.h>box.y&&b.x<box.x+box.w&&b.x+b.w>box.x)&&n.id!==this.hovered&&n.id!==this.selectedNodeId)continue;labels.push(box);ctx.fillStyle='#0b1422b8';ctx.fillRect(x-3,y-13,box.w+6,18);ctx.fillStyle=this.graph.color.get(n.root)||'#c2e4da';ctx.fillText(label,x,y);if(range){ctx.fillStyle='#b0c5c8';ctx.font='11px system-ui';ctx.fillText(ROLE_LABEL[n.role]+' · '+n.count+' 条',x,y+17);}}
  this.projected=points;this.lastDrawDuration=performance.now()-start;this.drawCount++;$('visibleCount').textContent=primary.length+' 个主层 · '+(nodes.length-primary.length)+' 个次层代表 / '+this.graph.texts.length+' 条资料';this.updateNavigation();
 }
 hit(x,y){let point=null,best=Infinity;for(const p of this.projected){if(p.lobes){const density=p.lobes.reduce((s,l)=>s+Math.exp(-((x-l.x)**2+(y-l.y)**2)/Math.max(1,2*(l.r*.48)**2)),0);if(density>.22&&best===Infinity)point=p;}else{const d=Math.hypot(x-p.x,y-p.y);if(d<Math.max(11,p.r+6)&&d<best){point=p;best=d;}}}if(!point&&this.contextPoint&&this.nav.scene.role!=='universe'&&!this.layerCounts.secondary){const c=this.contextPoint;if(c.lobes?c.lobes.some(l=>Math.hypot(x-l.x,y-l.y)<l.r*.75):Math.hypot(x-c.x,y-c.y)<c.r+5)point=c;}return point;}
 cancelTap(){clearTimeout(this.tapTimer);this.tapTimer=null;this.lastTap=null;}
 tap(p){const hit=this.hit(p.x,p.y);if(!hit){this.cancelTap();return;}const now=performance.now();if(this.lastTap?.id===hit.node.id&&now-this.lastTap.time<320){this.cancelTap();this.enter(hit.node);return;}this.cancelTap();this.lastTap={id:hit.node.id,time:now};this.tapTimer=setTimeout(()=>{this.onCard(hit.node);this.lastTap=null;},270);}
 zoom(amount,point){if(!this.nav)return;this.transition=null;const hit=point?this.hit(point.x,point.y):null,old=this.camera.zoom,next=clamp(old*amount,.03,200000);if(hit){const q=this.project(hit.world),vx=(q.x-this.W/2)/q.factor*(1-old/next),vy=(q.y-this.H/2)/q.factor*(1-old/next),cy=Math.cos(this.camera.yaw),sy=Math.sin(this.camera.yaw),cp=Math.cos(this.camera.pitch),sp=Math.sin(this.camera.pitch);this.camera.focus=this.camera.focus.map((x,i)=>x+[vx*cy+vy*sp*sy,vy*cp,vx*sy-vy*sp*cy][i]);}this.camera.zoom=next;this.dirty=true;const now=performance.now();if(amount>1&&hit&&this.nav.canEnter(hit.node,hit.node.radius*this.displayScale(hit.node)*this.project(hit.world).factor,[this.W,this.H],now)){this.enter(hit.node).then(ok=>{if(ok&&this.gestureCamera)this.nav.frame.returnCamera=copy(this.gestureCamera);});}else if(amount<1&&this.nav.canExit(100*this.nav.frame.scale*this.project(this.nav.frame.origin).factor,[this.W,this.H],now))this.exit();}
 events(){this.canvas.addEventListener('pointerdown',e=>{if(e.isTrusted)this.canvas.setPointerCapture(e.pointerId);const p=this.point(e);this.pointers.set(e.pointerId,{...p,start:p});this.drag=false;this.transition=null;if(this.pointers.size>1)this.cancelTap();});this.canvas.addEventListener('pointermove',e=>{const p=this.point(e),old=this.pointers.get(e.pointerId);if(old){if(Math.hypot(p.x-old.start.x,p.y-old.start.y)>5)this.drag=true;const before=[...this.pointers.values()];this.pointers.set(e.pointerId,{...p,start:old.start});if(this.pointers.size===2){const after=[...this.pointers.values()],a=Math.hypot(before[0].x-before[1].x,before[0].y-before[1].y),b=Math.hypot(after[0].x-after[1].x,after[0].y-after[1].y);if(a>0)this.zoom(b/a,{x:(after[0].x+after[1].x)/2,y:(after[0].y+after[1].y)/2});this.drag=true;}else if(this.drag){this.camera.yaw+=(p.x-old.x)*.007;this.camera.pitch=clamp(this.camera.pitch+(p.y-old.y)*.006,-1.4,1.4);this.cancelTap();}this.dirty=true;return;}const h=this.hit(p.x,p.y);this.hovered=h?.node.id||null;this.dirty=true;const hover=$('hover');hover.hidden=!h;hover.style.display=h?'block':'none';if(h){hover.textContent=ROLE_LABEL[h.node.role]+' · '+h.node.label;hover.style.left=clamp(p.x+14,8,this.W-235)+'px';hover.style.top=clamp(p.y+14,8,this.H-65)+'px';}});this.canvas.addEventListener('pointerup',e=>{const single=this.pointers.size===1,p=this.point(e);this.pointers.delete(e.pointerId);if(single&&!this.drag)this.tap(p);if(!this.pointers.size)this.drag=false;});this.canvas.addEventListener('pointercancel',e=>{this.pointers.delete(e.pointerId);this.cancelTap();});this.canvas.addEventListener('pointerleave',()=>{this.hovered=null;$('hover').style.display='none';this.dirty=true;});this.canvas.addEventListener('dblclick',e=>e.preventDefault());this.canvas.addEventListener('wheel',e=>{e.preventDefault();const now=performance.now();if(now-this.lastWheel>200)this.gestureCamera=copy(this.camera);this.lastWheel=now;this.zoom(Math.exp(-e.deltaY*.0016),this.point(e));},{passive:false});this.canvas.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('nodeCard').hidden)this.onCloseCard();else this.exit();}else if(e.key==='Enter'){const h=this.projected.find(p=>p.node.id===this.hovered);if(h)this.enter(h.node);}else if(e.key==='+'||e.key==='=')this.zoom(1.25);else if(e.key==='-')this.zoom(.8);else return;e.preventDefault();});}
 loop(t){const clock=this.clock();clock?.tick(t);if(this.consumeDirty())this.dirty=true;if(this.nav&&!document.hidden){const oldOrigin=this.nav.frame.origin.slice();this.updateFrames();const delta=this.nav.frame.origin.map((x,i)=>x-oldOrigin[i]);if(delta.some(x=>Math.abs(x)>1e-12)){this.camera.focus=this.camera.focus.map((x,i)=>x+delta[i]);if(this.transition){this.transition.from.focus=this.transition.from.focus.map((x,i)=>x+delta[i]);this.transition.to.focus=this.transition.to.focus.map((x,i)=>x+delta[i]);}}if(this.transition){const p=clamp((performance.now()-this.transition.start)/this.transition.duration,0,1),s=p*p*(3-2*p);this.camera.focus=this.transition.from.focus.map((x,i)=>mix(x,this.transition.to.focus[i],s));this.camera.zoom=Math.exp(mix(Math.log(this.transition.from.zoom),Math.log(this.transition.to.zoom),s));this.dirty=true;if(p===1)this.transition=null;}const animated=$('orbitEnabled').checked&&!clock?.paused&&(this.nav.scene.role==='system'||this.nav.scene.role==='planet'||this.projected.some(p=>p.layer===2&&p.node.role==='planet')),interval=this.W<600?50:33;if(animated&&t-this.lastDraw>=interval)this.dirty=true;if($('rotate').checked&&!this.pointers.size){this.camera.yaw+=Math.min(40,t-(this.lastTime||t))*.00006;this.dirty=true;}if(this.dirty&&this.W&&this.H){this.dirty=false;this.lastDraw=t;this.draw(t);}this.lastTime=t;}requestAnimationFrame(x=>this.loop(x));}
}
